"""Generate pytest test files from a StepFingerprint.

The generated test file is self-contained: it embeds the reference
fingerprint data and imports only build123d + OCCT. A user provides
their procedural implementation as a fixture.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Optional

from .fingerprint import StepFingerprint


def _fmt_float(v: float, decimals: int = 4) -> str:
    return f"{v:.{decimals}f}"


def _fmt_tuple(t: tuple, decimals: int = 4) -> str:
    return "(" + ", ".join(_fmt_float(v, decimals) for v in t) + ")"


def generate_test_file(
    fingerprint: StepFingerprint,
    output_path: Optional[str | Path] = None,
    module_name: str = "my_part",
    fixture_name: str = "part_under_test",
    axis: str = "Z",
    volume_tol_pct: float = 1.0,
    area_tol_pct: float = 2.0,
    bbox_tol_mm: float = 0.1,
    inertia_tol_pct: float = 2.0,
    cross_section_area_tol_pct: float = 3.0,
    cross_section_centroid_tol_mm: float = 0.2,
    radial_tol_mm: float = 0.15,
    face_area_tol_pct: float = 5.0,
) -> str:
    """Generate a pytest file that validates a Part against the fingerprint.

    The generated file expects a conftest.py fixture named `fixture_name`
    that returns a build123d Part to test.

    Args:
        fingerprint: Reference fingerprint to test against.
        output_path: If provided, write the test file here.
        module_name: Human-readable name for the part (used in comments).
        fixture_name: pytest fixture name that provides the Part under test.
        axis: Primary axis of the part (used in comments).
        volume_tol_pct: Volume tolerance in percent.
        area_tol_pct: Surface area tolerance in percent.
        bbox_tol_mm: Bounding box tolerance in mm.
        inertia_tol_pct: Moment of inertia tolerance in percent.
        cross_section_area_tol_pct: Cross-section area tolerance in percent.
        cross_section_centroid_tol_mm: Cross-section centroid tolerance in mm.
        radial_tol_mm: Radial profile tolerance in mm.
        face_area_tol_pct: Face area tolerance in percent.

    Returns:
        The generated test file content as a string.
    """
    fp = fingerprint
    va = fp.volume_and_area
    bb = fp.bounding_box
    moi = fp.moments_of_inertia
    topo = fp.topology

    lines = []

    # ── header ───────────────────────────────────────────────────────
    lines.append(f'"""Auto-generated geometric fingerprint tests for {module_name}.')
    lines.append("")
    lines.append(f"Generated by step-fingerprint from: {fp.file}")
    lines.append(f"Reference volume: {va['volume']:.4f} mm³")
    lines.append(f"Reference surface area: {va['surface_area']:.4f} mm²")
    lines.append(f"Reference bounding box: {_fmt_tuple(bb['size'])} mm")
    lines.append("")
    lines.append("To use these tests, create a conftest.py with a fixture::")
    lines.append("")
    lines.append(f"    @pytest.fixture")
    lines.append(f"    def {fixture_name}():")
    lines.append(f"        # Return the Part to validate.")
    lines.append(f"        return my_build_function()")
    lines.append("")
    lines.append("Any procedural implementation that passes all tests is")
    lines.append("geometrically equivalent to the reference STEP file.")
    lines.append('"""')
    lines.append("")

    # ── imports ──────────────────────────────────────────────────────
    lines.append("import math")
    lines.append("")
    lines.append("import pytest")
    lines.append("")
    lines.append("from build123d import Part")
    lines.append("from OCP.BRepAdaptor import BRepAdaptor_Surface")
    lines.append("from OCP.BRepAlgoAPI import BRepAlgoAPI_Section")
    lines.append("from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeFace")
    lines.append("from OCP.BRepGProp import BRepGProp")
    lines.append("from OCP.GeomAbs import (")
    lines.append("    GeomAbs_BSplineSurface, GeomAbs_Cone, GeomAbs_Cylinder,")
    lines.append("    GeomAbs_Plane, GeomAbs_Sphere, GeomAbs_Torus,")
    lines.append(")")
    lines.append("from OCP.GProp import GProp_GProps")
    lines.append("from OCP.IntCurvesFace import IntCurvesFace_ShapeIntersector")
    lines.append("from OCP.ShapeAnalysis import ShapeAnalysis_FreeBounds")
    lines.append("from OCP.TopAbs import TopAbs_EDGE, TopAbs_FACE, TopAbs_VERTEX")
    lines.append("from OCP.TopExp import TopExp_Explorer")
    lines.append("from OCP.TopTools import TopTools_HSequenceOfShape")
    lines.append("from OCP.TopoDS import TopoDS")
    lines.append("from OCP.gp import gp_Dir, gp_Lin, gp_Pln, gp_Pnt")
    lines.append("")
    lines.append("")

    # ── reference data ───────────────────────────────────────────────
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("# Reference fingerprint data")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("")

    lines.append(f"REF_VOLUME = {_fmt_float(va['volume'])}")
    lines.append(f"REF_SURFACE_AREA = {_fmt_float(va['surface_area'])}")
    lines.append(f"REF_CENTER_OF_MASS = {_fmt_tuple(va['center_of_mass'])}")
    lines.append(f"REF_BBOX_MIN = {_fmt_tuple(bb['min'])}")
    lines.append(f"REF_BBOX_MAX = {_fmt_tuple(bb['max'])}")
    lines.append(f"REF_BBOX_SIZE = {_fmt_tuple(bb['size'])}")
    lines.append("")

    lines.append("REF_INERTIA = {")
    for k in ("Ixx", "Iyy", "Izz", "Ixy", "Ixz", "Iyz"):
        lines.append(f'    "{k}": {_fmt_float(moi[k])},')
    lines.append("}")
    lines.append("")

    lines.append(f"REF_FACE_COUNT = {topo['faces']}")
    lines.append(f"REF_EDGE_COUNT = {topo['edges']}")
    lines.append(f"REF_VERTEX_COUNT = {topo['vertices']}")
    lines.append("")

    # Face inventory — group by type for readability
    lines.append("REF_FACE_INVENTORY = [")
    for f in fp.face_inventory:
        parts = [f'    {{"type": "{f["type"]}", "area": {_fmt_float(f["area"])}']
        if "diameter" in f:
            parts.append(f', "diameter": {_fmt_float(f["diameter"])}')
        if "radius" in f:
            parts.append(f', "radius": {_fmt_float(f["radius"])}')
        if "major_r" in f:
            parts.append(f', "major_r": {_fmt_float(f["major_r"])}')
            parts.append(f', "minor_r": {_fmt_float(f["minor_r"])}')
        if "semi_angle_deg" in f:
            parts.append(f', "semi_angle_deg": {_fmt_float(f["semi_angle_deg"], 2)}')
        parts.append("},")
        lines.append("".join(parts))
    lines.append("]")
    lines.append("")

    # Cross-sections
    lines.append("REF_CROSS_SECTIONS = [")
    for cs in fp.cross_sections:
        parts = [f'    {{"position": {_fmt_float(cs["position"])}, '
                 f'"area": {_fmt_float(cs["area"])}']
        # Add centroid keys dynamically
        for k, v in cs.items():
            if k.startswith("centroid_"):
                parts.append(f', "{k}": {_fmt_float(v)}')
        parts.append("},")
        lines.append("".join(parts))
    lines.append("]")
    lines.append("")

    # Radial profile
    lines.append("REF_RADIAL_PROFILE = [")
    for rp in fp.radial_profile:
        radii_str = ", ".join(
            f"{deg}: {_fmt_float(r) if r is not None else 'None'}"
            for deg, r in sorted(rp["radii"].items(), key=lambda x: float(x[0]))
        )
        lines.append(f'    {{"position": {_fmt_float(rp["position"])}, '
                     f'"radii": {{{radii_str}}}}},')
    lines.append("]")
    lines.append("")
    lines.append("")

    # ── helpers ───────────────────────────────────────────────────────
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("# Test helpers")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("")

    lines.append(textwrap.dedent("""\
    _SURFACE_NAMES = {
        GeomAbs_Plane: "Plane",
        GeomAbs_Cylinder: "Cylinder",
        GeomAbs_Cone: "Cone",
        GeomAbs_Sphere: "Sphere",
        GeomAbs_Torus: "Torus",
        GeomAbs_BSplineSurface: "BSpline",
    }


    def _get_face_inventory(shape):
        explorer = TopExp_Explorer(shape.wrapped, TopAbs_FACE)
        faces = []
        while explorer.More():
            face = TopoDS.Face_s(explorer.Current())
            adaptor = BRepAdaptor_Surface(face)
            stype = adaptor.GetType()
            type_name = _SURFACE_NAMES.get(stype, f"Other({stype})")
            props = GProp_GProps()
            BRepGProp.SurfaceProperties_s(face, props)
            info = {"type": type_name, "area": props.Mass()}
            if stype == GeomAbs_Cylinder:
                info["diameter"] = adaptor.Cylinder().Radius() * 2
            elif stype == GeomAbs_Sphere:
                info["radius"] = adaptor.Sphere().Radius()
            elif stype == GeomAbs_Torus:
                info["major_r"] = adaptor.Torus().MajorRadius()
                info["minor_r"] = adaptor.Torus().MinorRadius()
            elif stype == GeomAbs_Cone:
                info["semi_angle_deg"] = math.degrees(adaptor.Cone().SemiAngle())
            faces.append(info)
            explorer.Next()
        faces.sort(key=lambda f: (f["type"], -f["area"]))
        return faces


    def _cross_section_area(shape, axis_pos, plane_maker):
        plane = plane_maker(axis_pos)
        section = BRepAlgoAPI_Section(shape.wrapped, plane, False)
        section.ComputePCurveOn1(True)
        section.Approximation(True)
        section.Build()
        if not section.IsDone():
            return 0.0

        result_shape = section.Shape()
        edges_seq = TopTools_HSequenceOfShape()
        wires_seq = TopTools_HSequenceOfShape()
        edge_exp = TopExp_Explorer(result_shape, TopAbs_EDGE)
        while edge_exp.More():
            edges_seq.Append(edge_exp.Current())
            edge_exp.Next()
        if edges_seq.Length() == 0:
            return 0.0

        ShapeAnalysis_FreeBounds.ConnectEdgesToWires_s(
            edges_seq, 1e-4, False, wires_seq
        )
        total_area = 0.0
        for w_idx in range(1, wires_seq.Length() + 1):
            wire = TopoDS.Wire_s(wires_seq.Value(w_idx))
            try:
                face_maker = BRepBuilderAPI_MakeFace(plane, wire, True)
                if face_maker.IsDone():
                    face_props = GProp_GProps()
                    BRepGProp.SurfaceProperties_s(face_maker.Face(), face_props)
                    total_area += abs(face_props.Mass())
            except Exception:
                continue
        return total_area


    def _radial_distance(shape, origin, direction, max_r=20.0):
        line = gp_Lin(origin, direction)
        intersector = IntCurvesFace_ShapeIntersector()
        intersector.Load(shape.wrapped, 1e-6)
        intersector.PerformNearest(line, 0.0, max_r)
        if intersector.NbPnt() > 0:
            pt = intersector.Pnt(1)
            dx = pt.X() - origin.X()
            dy = pt.Y() - origin.Y()
            dz = pt.Z() - origin.Z()
            return math.sqrt(dx * dx + dy * dy + dz * dz)
        return None
    """))

    # ── test classes ─────────────────────────────────────────────────
    lines.append("")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append(f"# Tests for {module_name}")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("")

    # -- Global properties
    lines.append(f"class TestGlobalProperties:")
    lines.append(f'    """Volume, surface area, bounding box, center of mass."""')
    lines.append("")
    lines.append(f"    def test_volume(self, {fixture_name}):")
    lines.append(f"        vol_props = GProp_GProps()")
    lines.append(f"        BRepGProp.VolumeProperties_s({fixture_name}.wrapped, vol_props)")
    lines.append(f"        vol = vol_props.Mass()")
    lines.append(f"        assert abs(vol - REF_VOLUME) / REF_VOLUME < {volume_tol_pct / 100}, (")
    lines.append(f'            f"Volume {{vol:.4f}} differs from ref {{REF_VOLUME}} '
                 f'by {{abs(vol - REF_VOLUME) / REF_VOLUME * 100:.1f}}%"')
    lines.append(f"        )")
    lines.append("")

    lines.append(f"    def test_surface_area(self, {fixture_name}):")
    lines.append(f"        props = GProp_GProps()")
    lines.append(f"        BRepGProp.SurfaceProperties_s({fixture_name}.wrapped, props)")
    lines.append(f"        area = props.Mass()")
    lines.append(f"        assert abs(area - REF_SURFACE_AREA) / REF_SURFACE_AREA < {area_tol_pct / 100}, (")
    lines.append(f'            f"Surface area {{area:.4f}} differs from ref {{REF_SURFACE_AREA}}"')
    lines.append(f"        )")
    lines.append("")

    lines.append(f"    def test_bounding_box(self, {fixture_name}):")
    lines.append(f"        bb = {fixture_name}.bounding_box()")
    lines.append(f"        tol = {bbox_tol_mm}")
    for i, axis_name in enumerate(("X", "Y", "Z")):
        lines.append(f"        assert abs(bb.min.{axis_name} - REF_BBOX_MIN[{i}]) < tol, "
                     f'"BBox min {axis_name} mismatch"')
        lines.append(f"        assert abs(bb.max.{axis_name} - REF_BBOX_MAX[{i}]) < tol, "
                     f'"BBox max {axis_name} mismatch"')
    lines.append("")

    lines.append(f"    def test_center_of_mass(self, {fixture_name}):")
    lines.append(f"        props = GProp_GProps()")
    lines.append(f"        BRepGProp.VolumeProperties_s({fixture_name}.wrapped, props)")
    lines.append(f"        com = props.CentreOfMass()")
    lines.append(f"        for i, (actual, ref) in enumerate(zip(")
    lines.append(f"            (com.X(), com.Y(), com.Z()), REF_CENTER_OF_MASS)):")
    lines.append(f"            assert abs(actual - ref) < {bbox_tol_mm * 2}, (")
    lines.append(f'                f"CoM axis {{i}}: {{actual:.4f}} vs ref {{ref:.4f}}"')
    lines.append(f"            )")
    lines.append("")

    # -- Moments of inertia
    lines.append("")
    lines.append(f"class TestMomentsOfInertia:")
    lines.append(f'    """Inertia tensor — very sensitive to mass distribution."""')
    lines.append("")
    lines.append(f"    def test_principal_moments(self, {fixture_name}):")
    lines.append(f"        props = GProp_GProps()")
    lines.append(f"        BRepGProp.VolumeProperties_s({fixture_name}.wrapped, props)")
    lines.append(f"        mat = props.MatrixOfInertia()")
    lines.append(f"        for key, (r, c) in [(\"Ixx\", (1,1)), (\"Iyy\", (2,2)), (\"Izz\", (3,3))]:")
    lines.append(f"            actual = mat.Value(r, c)")
    lines.append(f"            ref = REF_INERTIA[key]")
    lines.append(f"            if abs(ref) > 1e-6:")
    lines.append(f"                assert abs(actual - ref) / abs(ref) < {inertia_tol_pct / 100}, (")
    lines.append(f'                    f"{{key}}: {{actual:.4f}} vs ref {{ref:.4f}}"')
    lines.append(f"                )")
    lines.append("")

    # -- Face inventory
    lines.append("")
    lines.append(f"class TestFaceInventory:")
    lines.append(f'    """Face types, counts, and key dimensions."""')
    lines.append("")
    lines.append(f"    def test_face_count(self, {fixture_name}):")
    lines.append(f"        faces = _get_face_inventory({fixture_name})")
    lines.append(f"        assert abs(len(faces) - REF_FACE_COUNT) <= 3, (")
    lines.append(f'            f"Face count {{len(faces)}} vs ref {{REF_FACE_COUNT}}"')
    lines.append(f"        )")
    lines.append("")

    lines.append(f"    def test_face_type_distribution(self, {fixture_name}):")
    lines.append(f"        faces = _get_face_inventory({fixture_name})")
    lines.append(f"        actual = {{}}")
    lines.append(f"        for f in faces:")
    lines.append(f'            actual[f["type"]] = actual.get(f["type"], 0) + 1')
    lines.append(f"        ref = {{}}")
    lines.append(f"        for f in REF_FACE_INVENTORY:")
    lines.append(f'            ref[f["type"]] = ref.get(f["type"], 0) + 1')
    lines.append(f"        for ftype, count in ref.items():")
    lines.append(f"            assert abs(actual.get(ftype, 0) - count) <= 2, (")
    lines.append(f'                f"{{ftype}} count: {{actual.get(ftype, 0)}} vs ref {{count}}"')
    lines.append(f"            )")
    lines.append("")

    lines.append(f"    def test_cylinder_diameters(self, {fixture_name}):")
    lines.append(f'        """Every reference cylinder diameter should appear."""')
    lines.append(f"        faces = _get_face_inventory({fixture_name})")
    lines.append(f'        actual_diams = sorted(f["diameter"] for f in faces if "diameter" in f)')
    lines.append(f'        ref_diams = sorted(f["diameter"] for f in REF_FACE_INVENTORY if "diameter" in f)')
    lines.append(f"        for rd in ref_diams:")
    lines.append(f"            assert any(abs(ad - rd) < 0.1 for ad in actual_diams), (")
    lines.append(f'                f"Reference cylinder d={{rd:.3f}} not found in actual: {{actual_diams}}"')
    lines.append(f"            )")
    lines.append("")

    # -- Cross-sections
    lines.append("")
    lines.append(f"class TestCrossSections:")
    lines.append(f'    """Cross-sectional area at {len(fp.cross_sections)} positions along {axis}."""')
    lines.append("")

    # Determine plane maker based on axis
    if axis.upper() == "Z":
        plane_maker = 'lambda v: gp_Pln(gp_Pnt(0, 0, v), gp_Dir(0, 0, 1))'
    elif axis.upper() == "Y":
        plane_maker = 'lambda v: gp_Pln(gp_Pnt(0, v, 0), gp_Dir(0, 1, 0))'
    else:
        plane_maker = 'lambda v: gp_Pln(gp_Pnt(v, 0, 0), gp_Dir(1, 0, 0))'

    lines.append(f"    _plane_maker = staticmethod({plane_maker})")
    lines.append("")

    lines.append(f"    @pytest.mark.parametrize(\"ref\", REF_CROSS_SECTIONS,")
    lines.append(f'        ids=[f"{axis}={{cs[\'position\']}}" for cs in REF_CROSS_SECTIONS])')
    lines.append(f"    def test_cross_section_area(self, {fixture_name}, ref):")
    lines.append(f"        area = _cross_section_area({fixture_name}, ref[\"position\"], self._plane_maker)")
    lines.append(f'        ref_area = ref["area"]')
    lines.append(f"        if ref_area < 0.01:  # near-zero slice")
    lines.append(f"            assert area < 0.5, f\"Expected ~0 area at pos={{ref['position']}}, got {{area:.4f}}\"")
    lines.append(f"        else:")
    lines.append(f"            assert abs(area - ref_area) / ref_area < {cross_section_area_tol_pct / 100}, (")
    lines.append(f'                f"Area at {axis}={{ref[\'position\']}}: {{area:.4f}} vs ref {{ref_area:.4f}} "')
    lines.append(f'                f"({{abs(area - ref_area) / ref_area * 100:.1f}}% off)"')
    lines.append(f"            )")
    lines.append("")

    # -- Radial profile
    lines.append("")
    lines.append(f"class TestRadialProfile:")
    lines.append(f'    """Radial distance from axis at {len(fp.radial_profile)} positions × '
                 f'{len(fp.radial_profile[0]["radii"]) if fp.radial_profile else 0} angles."""')
    lines.append("")

    if axis.upper() == "Z":
        origin_fn = "gp_Pnt(0, 0, pos)"
        dir_fn = "gp_Dir(math.cos(math.radians(deg)), math.sin(math.radians(deg)), 0)"
    elif axis.upper() == "Y":
        origin_fn = "gp_Pnt(0, pos, 0)"
        dir_fn = "gp_Dir(math.cos(math.radians(deg)), 0, math.sin(math.radians(deg)))"
    else:
        origin_fn = "gp_Pnt(pos, 0, 0)"
        dir_fn = "gp_Dir(0, math.cos(math.radians(deg)), math.sin(math.radians(deg)))"

    lines.append(f"    @pytest.mark.parametrize(\"ref\", REF_RADIAL_PROFILE,")
    lines.append(f'        ids=[f"{axis}={{rp[\'position\']}}" for rp in REF_RADIAL_PROFILE])')
    lines.append(f"    def test_radial_profile(self, {fixture_name}, ref):")
    lines.append(f'        pos = ref["position"]')
    lines.append(f'        for deg_str, ref_r in ref["radii"].items():')
    lines.append(f"            deg = float(deg_str)")
    lines.append(f"            if ref_r is None:")
    lines.append(f"                continue")
    lines.append(f"            origin = {origin_fn}")
    lines.append(f"            direction = {dir_fn}")
    lines.append(f"            actual_r = _radial_distance({fixture_name}, origin, direction)")
    lines.append(f"            assert actual_r is not None, (")
    lines.append(f'                f"No intersection at {axis}={{pos}}, angle={{deg}}°"')
    lines.append(f"            )")
    lines.append(f"            assert abs(actual_r - ref_r) < {radial_tol_mm}, (")
    lines.append(f'                f"Radial at {axis}={{pos}} angle={{deg}}°: '
                 f'{{actual_r:.4f}} vs ref {{ref_r:.4f}}"')
    lines.append(f"            )")
    lines.append("")

    content = "\n".join(lines)

    if output_path:
        Path(output_path).write_text(content)

    return content
