"""Auto-generated geometric fingerprint tests for crank.

Generated by cad-fingerprint from: examples/crank.stl
Reference volume: 8230.2040 mm³
Reference surface area: 3868.7450 mm²
Reference bounding box: (55.9950, 15.0000, 16.0000) mm

To use these tests, create a conftest.py with a fixture::

    @pytest.fixture
    def part_under_test():
        # Return the Part to validate.
        return my_build_function()

Any procedural implementation that passes all tests is
geometrically equivalent to the reference STL mesh.

Note: Face inventory tests are omitted (STL has no analytical
surface types). Cross-section and radial profile tests are fully
functional.
"""

import math

import pytest

from build123d import Part
from OCP.BRepAdaptor import BRepAdaptor_Curve, BRepAdaptor_Surface
from OCP.BRepAlgoAPI import BRepAlgoAPI_Section
from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeFace
from OCP.BRepGProp import BRepGProp
from OCP.GCPnts import GCPnts_AbscissaPoint
from OCP.GeomAbs import (
    GeomAbs_BSplineCurve, GeomAbs_BSplineSurface, GeomAbs_Circle,
    GeomAbs_Cone, GeomAbs_Cylinder, GeomAbs_Ellipse,
    GeomAbs_Line, GeomAbs_Plane, GeomAbs_Sphere, GeomAbs_Torus,
)
from OCP.GProp import GProp_GProps
from OCP.IntCurvesFace import IntCurvesFace_ShapeIntersector
from OCP.ShapeAnalysis import ShapeAnalysis_FreeBounds
from OCP.TopAbs import TopAbs_EDGE, TopAbs_FACE, TopAbs_VERTEX
from OCP.TopExp import TopExp_Explorer
from OCP.TopTools import TopTools_HSequenceOfShape
from OCP.TopoDS import TopoDS
from OCP.gp import gp_Dir, gp_Lin, gp_Pln, gp_Pnt


# ═══════════════════════════════════════════════════════════
# Reference fingerprint data
# ═══════════════════════════════════════════════════════════

REF_VOLUME = 8230.2040
REF_SURFACE_AREA = 3868.7450
REF_CENTER_OF_MASS = (17.6168, 45.5000, 62.9875)
REF_BBOX_MIN = (-7.9975, 38.0000, 55.0500)
REF_BBOX_MAX = (47.9975, 53.0000, 71.0500)
REF_BBOX_SIZE = (55.9950, 15.0000, 16.0000)

REF_INERTIA = {
    "Ixx": 273430.3485,
    "Iyy": 2142180.7884,
    "Izz": 2181015.6360,
    "Ixy": 0.0023,
    "Ixz": -9061.2886,
    "Iyz": -0.0011,
}

REF_EDGE_INVENTORY = [
]

REF_CROSS_SECTIONS = [
    {"position": 55.2100, "area": 95.4558, "centroid_x": 20.0000, "centroid_y": 45.5000},
    {"position": 56.0353, "area": 230.7018, "centroid_x": 20.0000, "centroid_y": 45.5000},
    {"position": 56.8605, "area": 303.9464, "centroid_x": 20.0000, "centroid_y": 45.5000},
    {"position": 57.6858, "area": 355.9643, "centroid_x": 20.0000, "centroid_y": 45.5000},
    {"position": 58.5111, "area": 721.5074, "centroid_x": 17.8922, "centroid_y": 45.5000},
    {"position": 59.3363, "area": 703.3389, "centroid_x": 16.8953, "centroid_y": 45.5000},
    {"position": 60.1616, "area": 694.1012, "centroid_x": 16.2632, "centroid_y": 45.5000},
    {"position": 60.9868, "area": 688.6574, "centroid_x": 15.8422, "centroid_y": 45.5000},
    {"position": 61.8121, "area": 638.4489, "centroid_x": 16.7301, "centroid_y": 45.5000},
    {"position": 62.6374, "area": 625.4467, "centroid_x": 16.9058, "centroid_y": 45.5000},
    {"position": 63.4626, "area": 625.4468, "centroid_x": 16.9058, "centroid_y": 45.5000},
    {"position": 64.2879, "area": 638.3302, "centroid_x": 16.7332, "centroid_y": 45.5000},
    {"position": 65.1132, "area": 705.9999, "centroid_x": 15.4531, "centroid_y": 45.5000},
    {"position": 65.9384, "area": 711.4449, "centroid_x": 15.8668, "centroid_y": 45.5000},
    {"position": 66.7637, "area": 720.6832, "centroid_x": 16.4887, "centroid_y": 45.5000},
    {"position": 67.5889, "area": 738.8522, "centroid_x": 17.4722, "centroid_y": 45.5000},
    {"position": 68.4142, "area": 373.3085, "centroid_x": 19.0708, "centroid_y": 45.5000},
    {"position": 69.2395, "area": 321.2903, "centroid_x": 18.9204, "centroid_y": 45.5000},
    {"position": 70.0647, "area": 248.0446, "centroid_x": 18.6016, "centroid_y": 45.5000},
    {"position": 70.8900, "area": 80.1067, "centroid_x": 23.8324, "centroid_y": 45.5000},
]

REF_RADIAL_PROFILE = [
    {"position": 55.2100, "radii": {0.0: 21.5918, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 21.5918, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 56.3300, "radii": {0.0: 24.3361, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 24.3361, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 57.4500, "radii": {0.0: 25.7123, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 25.7123, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 58.5700, "radii": {0.0: 26.6250, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 26.6250, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 59.6900, "radii": {0.0: 27.2584, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 27.2584, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 60.8100, "radii": {0.0: 27.6784, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 27.6784, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 61.9300, "radii": {0.0: 27.9190, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 27.9190, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 63.0500, "radii": {0.0: 27.9975, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 27.9975, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 64.1700, "radii": {0.0: 27.9190, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 27.9190, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 65.2900, "radii": {0.0: 27.6784, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 27.6784, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 66.4100, "radii": {0.0: 27.2584, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 27.2584, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 67.5300, "radii": {0.0: 26.6250, 30.0: 15.0000, 60.0: 8.6603, 90.0: 7.5000, 120.0: 8.6603, 150.0: 15.0000, 180.0: 26.6250, 210.0: 15.0000, 240.0: 8.6603, 270.0: 7.5000, 300.0: 8.6603, 330.0: 15.0000}},
    {"position": 68.6500, "radii": {0.0: 25.7123, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 25.7123, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 69.7700, "radii": {0.0: 24.3361, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 24.3361, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": 70.8900, "radii": {0.0: 21.5918, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: None, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
]


# ═══════════════════════════════════════════════════════════
# Test helpers
# ═══════════════════════════════════════════════════════════

_SURFACE_NAMES = {
    GeomAbs_Plane: "Plane",
    GeomAbs_Cylinder: "Cylinder",
    GeomAbs_Cone: "Cone",
    GeomAbs_Sphere: "Sphere",
    GeomAbs_Torus: "Torus",
    GeomAbs_BSplineSurface: "BSpline",
}


def _get_face_inventory(shape):
    explorer = TopExp_Explorer(shape.wrapped, TopAbs_FACE)
    faces = []
    while explorer.More():
        face = TopoDS.Face_s(explorer.Current())
        adaptor = BRepAdaptor_Surface(face)
        stype = adaptor.GetType()
        type_name = _SURFACE_NAMES.get(stype, f"Other({stype})")
        props = GProp_GProps()
        BRepGProp.SurfaceProperties_s(face, props)
        info = {"type": type_name, "area": props.Mass()}
        if stype == GeomAbs_Cylinder:
            info["diameter"] = adaptor.Cylinder().Radius() * 2
        elif stype == GeomAbs_Sphere:
            info["radius"] = adaptor.Sphere().Radius()
        elif stype == GeomAbs_Torus:
            info["major_r"] = adaptor.Torus().MajorRadius()
            info["minor_r"] = adaptor.Torus().MinorRadius()
        elif stype == GeomAbs_Cone:
            info["semi_angle_deg"] = math.degrees(adaptor.Cone().SemiAngle())
        faces.append(info)
        explorer.Next()
    faces.sort(key=lambda f: (f["type"], -f["area"]))
    return faces


_CURVE_NAMES = {
    GeomAbs_Line: "Line",
    GeomAbs_Circle: "Circle",
    GeomAbs_Ellipse: "Ellipse",
    GeomAbs_BSplineCurve: "BSpline",
}


def _get_edge_inventory(shape):
    explorer = TopExp_Explorer(shape.wrapped, TopAbs_EDGE)
    edges = []
    while explorer.More():
        edge = TopoDS.Edge_s(explorer.Current())
        adaptor = BRepAdaptor_Curve(edge)
        ctype = adaptor.GetType()
        type_name = _CURVE_NAMES.get(ctype, f"Other({int(ctype)})")
        length = GCPnts_AbscissaPoint.Length_s(adaptor)
        info = {"type": type_name, "length": length}
        if ctype == GeomAbs_Circle:
            info["radius"] = adaptor.Circle().Radius()
        edges.append(info)
        explorer.Next()
    edges.sort(key=lambda e: (e["type"], -e["length"]))
    return edges


def _cross_section_props(shape, axis_pos, plane_maker, uv_axes):
    # Return area, centroid, and 2D shape moments for a cross-section.
    _axis_idx = {"X": 1, "Y": 2, "Z": 3}
    u_idx = _axis_idx[uv_axes[0]]
    v_idx = _axis_idx[uv_axes[1]]
    zero = {"area": 0.0, "centroid_u": 0.0, "centroid_v": 0.0,
            "Iuu_2d": 0.0, "Ivv_2d": 0.0}
    plane = plane_maker(axis_pos)
    section = BRepAlgoAPI_Section(shape.wrapped, plane, False)
    section.ComputePCurveOn1(True)
    section.Approximation(True)
    section.Build()
    if not section.IsDone():
        return zero

    result_shape = section.Shape()
    edges_seq = TopTools_HSequenceOfShape()
    wires_seq = TopTools_HSequenceOfShape()
    edge_exp = TopExp_Explorer(result_shape, TopAbs_EDGE)
    while edge_exp.More():
        edges_seq.Append(edge_exp.Current())
        edge_exp.Next()
    if edges_seq.Length() == 0:
        return zero

    ShapeAnalysis_FreeBounds.ConnectEdgesToWires_s(
        edges_seq, 1e-4, False, wires_seq
    )
    total_area = 0.0
    total_cu = 0.0
    total_cv = 0.0
    total_Iuu = 0.0
    total_Ivv = 0.0
    for w_idx in range(1, wires_seq.Length() + 1):
        wire = TopoDS.Wire_s(wires_seq.Value(w_idx))
        try:
            face_maker = BRepBuilderAPI_MakeFace(plane, wire, True)
            if face_maker.IsDone():
                face_shape = face_maker.Face()
                face_props = GProp_GProps()
                BRepGProp.SurfaceProperties_s(face_shape, face_props)
                a = abs(face_props.Mass())
                com = face_props.CentreOfMass()
                u = getattr(com, uv_axes[0])()
                v = getattr(com, uv_axes[1])()
                total_area += a
                total_cu += u * a
                total_cv += v * a
                mat = face_props.MatrixOfInertia()
                total_Iuu += mat.Value(u_idx, u_idx)
                total_Ivv += mat.Value(v_idx, v_idx)
        except Exception:
            continue
    cu = total_cu / total_area if total_area > 1e-9 else 0.0
    cv = total_cv / total_area if total_area > 1e-9 else 0.0
    return {"area": total_area, "centroid_u": cu, "centroid_v": cv,
            "Iuu_2d": total_Iuu, "Ivv_2d": total_Ivv}


def _radial_distance(shape, origin, direction, max_r=20.0):
    line = gp_Lin(origin, direction)
    intersector = IntCurvesFace_ShapeIntersector()
    intersector.Load(shape.wrapped, 1e-6)
    intersector.PerformNearest(line, 0.0, max_r)
    if intersector.NbPnt() > 0:
        pt = intersector.Pnt(1)
        dx = pt.X() - origin.X()
        dy = pt.Y() - origin.Y()
        dz = pt.Z() - origin.Z()
        return math.sqrt(dx * dx + dy * dy + dz * dz)
    return None


# ═══════════════════════════════════════════════════════════
# Tests for crank
# ═══════════════════════════════════════════════════════════

class TestGlobalProperties:
    """Volume, surface area, bounding box, center of mass."""

    def test_volume(self, part_under_test):
        vol_props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, vol_props)
        vol = vol_props.Mass()
        pct = abs(vol - REF_VOLUME) / REF_VOLUME * 100
        direction = 'larger' if vol > REF_VOLUME else 'smaller'
        assert pct / 100 < 0.01, (
            f"Volume {vol:.4f} is {direction} than ref {REF_VOLUME} by {abs(vol - REF_VOLUME):.2f} mm³ ({pct:.1f}%) — adjust overall dimensions"
        )

    def test_surface_area(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.SurfaceProperties_s(part_under_test.wrapped, props)
        area = props.Mass()
        pct = abs(area - REF_SURFACE_AREA) / REF_SURFACE_AREA * 100
        direction = 'larger' if area > REF_SURFACE_AREA else 'smaller'
        assert pct / 100 < 0.02, (
            f"Surface area {area:.4f} is {direction} than ref {REF_SURFACE_AREA} ({pct:.1f}% off) — check feature dimensions"
        )

    def test_bounding_box(self, part_under_test):
        bb = part_under_test.bounding_box()
        tol = 0.1
        assert abs(bb.min.X - REF_BBOX_MIN[0]) < tol, "BBox min X mismatch"
        assert abs(bb.max.X - REF_BBOX_MAX[0]) < tol, "BBox max X mismatch"
        assert abs(bb.min.Y - REF_BBOX_MIN[1]) < tol, "BBox min Y mismatch"
        assert abs(bb.max.Y - REF_BBOX_MAX[1]) < tol, "BBox max Y mismatch"
        assert abs(bb.min.Z - REF_BBOX_MIN[2]) < tol, "BBox min Z mismatch"
        assert abs(bb.max.Z - REF_BBOX_MAX[2]) < tol, "BBox max Z mismatch"

    def test_center_of_mass(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, props)
        com = props.CentreOfMass()
        for i, (actual, ref) in enumerate(zip(
            (com.X(), com.Y(), com.Z()), REF_CENTER_OF_MASS)):
            assert abs(actual - ref) < 0.2, (
                f"CoM axis {i}: {actual:.4f} vs ref {ref:.4f}"
            )


class TestMomentsOfInertia:
    """Inertia tensor — very sensitive to mass distribution."""

    def test_principal_moments(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, props)
        mat = props.MatrixOfInertia()
        for key, (r, c) in [("Ixx", (1,1)), ("Iyy", (2,2)), ("Izz", (3,3))]:
            actual = mat.Value(r, c)
            ref = REF_INERTIA[key]
            if abs(ref) > 1e-6:
                pct = abs(actual - ref) / abs(ref) * 100
                assert pct / 100 < 0.02, (
                    f"{key}: {actual:.4f} vs ref {ref:.4f} ({pct:.1f}% off) — mass distribution differs"
                )

    def test_off_diagonal_moments(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, props)
        mat = props.MatrixOfInertia()
        for key, (r, c) in [("Ixy", (1,2)), ("Ixz", (1,3)), ("Iyz", (2,3))]:
            actual = mat.Value(r, c)
            ref = REF_INERTIA[key]
            tol = max(abs(ref) * 0.02, 1.0)
            assert abs(actual - ref) < tol, (
                f"{key}: {actual:.4f} vs ref {ref:.4f} — part may be rotated or asymmetric"
            )


class TestCrossSections:
    """Cross-sectional area and centroid at 20 positions along Z."""

    _plane_maker = staticmethod(lambda v: gp_Pln(gp_Pnt(0, 0, v), gp_Dir(0, 0, 1)))
    _uv_axes = ("X", "Y")

    @pytest.mark.parametrize("ref", REF_CROSS_SECTIONS,
        ids=[f"Z={cs['position']}" for cs in REF_CROSS_SECTIONS])
    def test_cross_section_area(self, part_under_test, ref):
        props = _cross_section_props(part_under_test, ref["position"], self._plane_maker, self._uv_axes)
        area = props["area"]
        ref_area = ref["area"]
        if ref_area < 0.01:  # near-zero slice
            assert area < 0.5, f"Expected ~0 area at pos={ref['position']}, got {area:.4f}"
        else:
            pct = abs(area - ref_area) / ref_area * 100
            direction = 'too large' if area > ref_area else 'too small'
            assert pct / 100 < 0.03, (
                f"Area at Z={ref['position']}: {area:.4f} vs ref {ref_area:.4f} "
                f"({pct:.1f}% {direction}) — adjust radius/fillet at this position"
            )

    @pytest.mark.parametrize("ref", REF_CROSS_SECTIONS,
        ids=[f"Z={cs['position']}" for cs in REF_CROSS_SECTIONS])
    def test_cross_section_centroid(self, part_under_test, ref):
        ref_area = ref["area"]
        if ref_area < 0.01:
            pytest.skip("near-zero area — centroid meaningless")
        props = _cross_section_props(part_under_test, ref["position"], self._plane_maker, self._uv_axes)
        for ref_key, prop_key in [("centroid_x", "centroid_u"), ("centroid_y", "centroid_v")]:
            actual = props[prop_key]
            ref_val = ref[ref_key]
            diff = actual - ref_val
            assert abs(diff) < 0.2, (
                f"Centroid {ref_key} at Z={ref['position']}: {actual:.4f} vs ref {ref_val:.4f} "
                f"(shifted {'positive' if diff > 0 else 'negative'} by {abs(diff):.3f}mm) — check alignment"
            )

    @pytest.mark.parametrize("ref", REF_CROSS_SECTIONS,
        ids=[f"Z={cs['position']}" for cs in REF_CROSS_SECTIONS])
    def test_cross_section_shape(self, part_under_test, ref):
        """2D moments capture cross-section shape, not just area."""
        ref_area = ref["area"]
        if ref_area < 0.01:
            pytest.skip("near-zero area — shape moments meaningless")
        props = _cross_section_props(part_under_test, ref["position"], self._plane_maker, self._uv_axes)
        for ref_key, prop_key in [("Ixx_2d", "Iuu_2d"), ("Iyy_2d", "Ivv_2d")]:
            ref_val = ref.get(ref_key, 0.0)
            if abs(ref_val) < 0.01:
                continue
            actual = props[prop_key]
            pct = abs(actual - ref_val) / abs(ref_val) * 100
            assert pct / 100 < 0.05, (
                f"Shape moment {ref_key} at Z={ref['position']}: {actual:.4f} vs ref {ref_val:.4f} "
                f"({pct:.1f}% off) — cross-section shape differs"
            )


class TestRadialProfile:
    """Radial distance from axis at 15 positions × 12 angles."""

    @pytest.mark.parametrize("ref", REF_RADIAL_PROFILE,
        ids=[f"Z={rp['position']}" for rp in REF_RADIAL_PROFILE])
    def test_radial_profile(self, part_under_test, ref):
        pos = ref["position"]
        for deg_str, ref_r in ref["radii"].items():
            deg = float(deg_str)
            if ref_r is None:
                continue
            origin = gp_Pnt(0, 0, pos)
            direction = gp_Dir(math.cos(math.radians(deg)), math.sin(math.radians(deg)), 0)
            actual_r = _radial_distance(part_under_test, origin, direction)
            assert actual_r is not None, (
                f"No intersection at Z={pos}, angle={deg}°"
            )
            hint = 'excess' if actual_r > ref_r else 'missing'
            assert abs(actual_r - ref_r) < 0.15, (
                f"Radial at Z={pos} angle={deg}°: {actual_r:.4f} vs ref {ref_r:.4f} — {hint} material"
            )


class TestBuildQuality:
    """Solid validity, watertight check, single body."""

    def test_single_solid(self, part_under_test):
        """Result must be a single solid (not split by failed booleans)."""
        from OCP.TopAbs import TopAbs_SOLID
        exp = TopExp_Explorer(part_under_test.wrapped, TopAbs_SOLID)
        count = 0
        while exp.More():
            count += 1
            exp.Next()
        assert count == 1, (
            f"Expected 1 solid(s), got {count}"
        )

    def test_no_free_edges(self, part_under_test):
        """No free edges — the solid must be watertight."""
        from OCP.ShapeAnalysis import ShapeAnalysis_FreeBounds
        fb = ShapeAnalysis_FreeBounds(part_under_test.wrapped)
        open_wires = fb.GetOpenWires()
        exp = TopExp_Explorer(open_wires, TopAbs_EDGE)
        free_count = 0
        while exp.More():
            free_count += 1
            exp.Next()
        assert free_count == 0, (
            f"Found {free_count} free edge(s) — solid is not watertight"
        )

    def test_shape_valid(self, part_under_test):
        """OCCT validity check — no degenerate or corrupt geometry."""
        from OCP.BRepCheck import BRepCheck_Analyzer
        analyzer = BRepCheck_Analyzer(part_under_test.wrapped)
        assert analyzer.IsValid(), "BRepCheck_Analyzer reports invalid geometry"
