"""Auto-generated geometric fingerprint tests for peghead.

Generated by step-fingerprint from: /app/workspaces/pzfreo/gib-tuners-mk2/reference/peghead7mm.step
Reference volume: 375.6419 mm³
Reference surface area: 568.3970 mm²
Reference bounding box: (12.5000, 8.5000, 29.4260) mm

To use these tests, create a conftest.py with a fixture::

    @pytest.fixture
    def part_under_test():
        # Return the Part to validate.
        return my_build_function()

Any procedural implementation that passes all tests is
geometrically equivalent to the reference STEP file.
"""

import math

import pytest

from build123d import Part
from OCP.BRepAdaptor import BRepAdaptor_Surface
from OCP.BRepAlgoAPI import BRepAlgoAPI_Section
from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeFace
from OCP.BRepGProp import BRepGProp
from OCP.GeomAbs import (
    GeomAbs_BSplineSurface, GeomAbs_Cone, GeomAbs_Cylinder,
    GeomAbs_Plane, GeomAbs_Sphere, GeomAbs_Torus,
)
from OCP.GProp import GProp_GProps
from OCP.IntCurvesFace import IntCurvesFace_ShapeIntersector
from OCP.ShapeAnalysis import ShapeAnalysis_FreeBounds
from OCP.TopAbs import TopAbs_EDGE, TopAbs_FACE, TopAbs_VERTEX
from OCP.TopExp import TopExp_Explorer
from OCP.TopTools import TopTools_HSequenceOfShape
from OCP.TopoDS import TopoDS
from OCP.gp import gp_Dir, gp_Lin, gp_Pln, gp_Pnt


# ═══════════════════════════════════════════════════════════
# Reference fingerprint data
# ═══════════════════════════════════════════════════════════

REF_VOLUME = 375.6419
REF_SURFACE_AREA = 568.3970
REF_CENTER_OF_MASS = (0.0001, -0.0000, -2.8360)
REF_BBOX_MIN = (-6.2500, -4.2500, -19.0260)
REF_BBOX_MAX = (6.2500, 4.2500, 10.4000)
REF_BBOX_SIZE = (12.5000, 8.5000, 29.4260)

REF_INERTIA = {
    "Ixx": 20339.6797,
    "Iyy": 22246.9700,
    "Izz": 2959.4089,
    "Ixy": -0.0328,
    "Ixz": 0.1634,
    "Iyz": 0.1209,
}

REF_FACE_COUNT = 27
REF_EDGE_COUNT = 122
REF_VERTEX_COUNT = 244

REF_FACE_INVENTORY = [
    {"type": "BSpline", "area": 16.8890},
    {"type": "BSpline", "area": 16.8890},
    {"type": "BSpline", "area": 14.8222},
    {"type": "BSpline", "area": 14.8222},
    {"type": "BSpline", "area": 2.0483},
    {"type": "BSpline", "area": 2.0262},
    {"type": "Cylinder", "area": 124.1557, "diameter": 3.8000},
    {"type": "Cylinder", "area": 68.5156, "diameter": 9.8000},
    {"type": "Cylinder", "area": 26.3894, "diameter": 7.0000},
    {"type": "Cylinder", "area": 3.9584, "diameter": 2.1000},
    {"type": "Cylinder", "area": 0.4587, "diameter": 1.0000},
    {"type": "Cylinder", "area": 0.0099, "diameter": 0.5970},
    {"type": "Cylinder", "area": 0.0099, "diameter": 0.5969},
    {"type": "Plane", "area": 27.9485},
    {"type": "Plane", "area": 27.9483},
    {"type": "Plane", "area": 27.1434},
    {"type": "Plane", "area": 18.2605},
    {"type": "Plane", "area": 11.3411},
    {"type": "Plane", "area": 10.2968},
    {"type": "Plane", "area": 1.7671},
    {"type": "Plane", "area": 0.9817},
    {"type": "Sphere", "area": 73.8977, "radius": 6.2500},
    {"type": "Torus", "area": 45.7013, "major_r": 2.5179, "minor_r": 2.0000},
    {"type": "Torus", "area": 13.2776, "major_r": 5.8435, "minor_r": 0.3000},
    {"type": "Torus", "area": 13.2660, "major_r": 5.8435, "minor_r": 0.3000},
    {"type": "Torus", "area": 2.7861, "major_r": 0.7500, "minor_r": 0.3000},
    {"type": "Torus", "area": 2.7861, "major_r": 0.7500, "minor_r": 0.3000},
]

REF_CROSS_SECTIONS = [
    {"position": -18.7317, "area": 3.4632, "centroid_x": 0.0000, "centroid_y": -0.0000},
    {"position": -17.2140, "area": 11.0836, "centroid_x": 0.0034, "centroid_y": 0.0015},
    {"position": -15.6962, "area": 8.3978, "centroid_x": 0.0000, "centroid_y": -0.0000},
    {"position": -14.1784, "area": 6.9813, "centroid_x": -0.0000, "centroid_y": -0.0000},
    {"position": -12.6607, "area": 6.9054, "centroid_x": -0.0000, "centroid_y": -0.0000},
    {"position": -11.1429, "area": 7.4360, "centroid_x": 0.0000, "centroid_y": -0.0000},
    {"position": -9.6252, "area": 8.6545, "centroid_x": -0.0000, "centroid_y": -0.0000},
    {"position": -8.1074, "area": 11.3783, "centroid_x": -0.0000, "centroid_y": -0.0000},
    {"position": -6.5896, "area": 24.2506, "centroid_x": -0.0000, "centroid_y": -0.0000},
    {"position": -5.0719, "area": 13.0161, "centroid_x": 0.0000, "centroid_y": -0.0000},
    {"position": -3.5541, "area": 9.9224, "centroid_x": -0.0000, "centroid_y": -0.0000},
    {"position": -2.0364, "area": 34.4257, "centroid_x": -0.0000, "centroid_y": 0.0000},
    {"position": -0.5186, "area": 38.4845, "centroid_x": -0.0000, "centroid_y": -0.0000},
    {"position": 0.9992, "area": 11.3411, "centroid_x": 0.0000, "centroid_y": 0.0000},
    {"position": 2.5169, "area": 11.3411, "centroid_x": 0.0000, "centroid_y": 0.0000},
    {"position": 4.0347, "area": 11.3411, "centroid_x": 0.0000, "centroid_y": 0.0000},
    {"position": 5.5525, "area": 11.3411, "centroid_x": 0.0000, "centroid_y": 0.0000},
    {"position": 7.0702, "area": 11.3411, "centroid_x": 0.0000, "centroid_y": 0.0000},
    {"position": 8.5880, "area": 11.3411, "centroid_x": 0.0000, "centroid_y": 0.0000},
    {"position": 10.1057, "area": 11.3411, "centroid_x": 0.0000, "centroid_y": 0.0000},
]

REF_RADIAL_PROFILE = [
    {"position": -18.7317, "radii": {0.0: 1.0499, 30.0: 1.0499, 60.0: 1.0499, 90.0: 1.0499, 120.0: 1.0499, 150.0: 1.0499, 180.0: 1.0499, 210.0: 1.0499, 240.0: 1.0499, 270.0: 1.0499, 300.0: 1.0499, 330.0: 1.0499}},
    {"position": -16.6719, "radii": {0.0: 3.4343, 30.0: 2.4730, 60.0: 1.3503, 90.0: 1.1231, 120.0: 1.3503, 150.0: 2.4730, 180.0: 3.4343, 210.0: 2.4730, 240.0: 1.3503, 270.0: 1.1231, 300.0: 1.3503, 330.0: 2.4730}},
    {"position": -14.6121, "radii": {0.0: 3.9408, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 3.9408, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": -12.5523, "radii": {0.0: 4.8253, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 4.8253, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": -10.4925, "radii": {0.0: 4.7489, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 4.7489, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": -8.4326, "radii": {0.0: 3.6516, 30.0: None, 60.0: None, 90.0: None, 120.0: None, 150.0: None, 180.0: 3.6516, 210.0: None, 240.0: None, 270.0: None, 300.0: None, 330.0: None}},
    {"position": -6.3728, "radii": {0.0: 3.6448, 30.0: 3.2039, 60.0: 1.8498, 90.0: 1.6019, 120.0: 1.8498, 150.0: 3.2039, 180.0: 3.6448, 210.0: 3.2039, 240.0: 1.8498, 270.0: 1.6019, 300.0: 1.8498, 330.0: 3.2039}},
    {"position": -4.3130, "radii": {0.0: 1.8977, 30.0: 1.8977, 60.0: 1.8958, 90.0: 1.6750, 120.0: 1.8958, 150.0: 1.8977, 180.0: 1.8977, 210.0: 1.8977, 240.0: 1.8958, 270.0: 1.6750, 300.0: 1.8958, 330.0: 1.8977}},
    {"position": -2.2532, "radii": {0.0: 1.7500, 30.0: 1.7500, 60.0: 1.7496, 90.0: 1.7481, 120.0: 1.7496, 150.0: 1.7500, 180.0: 1.7500, 210.0: 1.7500, 240.0: 1.7496, 270.0: 1.7481, 300.0: 1.7496, 330.0: 1.7500}},
    {"position": -0.1934, "radii": {0.0: 3.5000, 30.0: 3.5000, 60.0: 3.5000, 90.0: 3.5000, 120.0: 3.5000, 150.0: 3.5000, 180.0: 3.5000, 210.0: 3.5000, 240.0: 3.5000, 270.0: 3.5000, 300.0: 3.5000, 330.0: 3.5000}},
    {"position": 1.8665, "radii": {0.0: 1.9000, 30.0: 1.9000, 60.0: 1.9000, 90.0: 1.9000, 120.0: 1.9000, 150.0: 1.9000, 180.0: 1.9000, 210.0: 1.9000, 240.0: 1.9000, 270.0: 1.9000, 300.0: 1.9000, 330.0: 1.9000}},
    {"position": 3.9263, "radii": {0.0: 1.9000, 30.0: 1.9000, 60.0: 1.9000, 90.0: 1.9000, 120.0: 1.9000, 150.0: 1.9000, 180.0: 1.9000, 210.0: 1.9000, 240.0: 1.9000, 270.0: 1.9000, 300.0: 1.9000, 330.0: 1.9000}},
    {"position": 5.9861, "radii": {0.0: 1.9000, 30.0: 1.9000, 60.0: 1.9000, 90.0: 1.9000, 120.0: 1.9000, 150.0: 1.9000, 180.0: 1.9000, 210.0: 1.9000, 240.0: 1.9000, 270.0: 1.9000, 300.0: 1.9000, 330.0: 1.9000}},
    {"position": 8.0459, "radii": {0.0: 1.9000, 30.0: 1.9000, 60.0: 1.9000, 90.0: 1.9000, 120.0: 1.9000, 150.0: 1.9000, 180.0: 1.9000, 210.0: 1.9000, 240.0: 1.9000, 270.0: 1.9000, 300.0: 1.9000, 330.0: 1.9000}},
    {"position": 10.1057, "radii": {0.0: 1.9000, 30.0: 1.9000, 60.0: 1.9000, 90.0: 1.9000, 120.0: 1.9000, 150.0: 1.9000, 180.0: 1.9000, 210.0: 1.9000, 240.0: 1.9000, 270.0: 1.9000, 300.0: 1.9000, 330.0: 1.9000}},
]


# ═══════════════════════════════════════════════════════════
# Test helpers
# ═══════════════════════════════════════════════════════════

_SURFACE_NAMES = {
    GeomAbs_Plane: "Plane",
    GeomAbs_Cylinder: "Cylinder",
    GeomAbs_Cone: "Cone",
    GeomAbs_Sphere: "Sphere",
    GeomAbs_Torus: "Torus",
    GeomAbs_BSplineSurface: "BSpline",
}


def _get_face_inventory(shape):
    explorer = TopExp_Explorer(shape.wrapped, TopAbs_FACE)
    faces = []
    while explorer.More():
        face = TopoDS.Face_s(explorer.Current())
        adaptor = BRepAdaptor_Surface(face)
        stype = adaptor.GetType()
        type_name = _SURFACE_NAMES.get(stype, f"Other({stype})")
        props = GProp_GProps()
        BRepGProp.SurfaceProperties_s(face, props)
        info = {"type": type_name, "area": props.Mass()}
        if stype == GeomAbs_Cylinder:
            info["diameter"] = adaptor.Cylinder().Radius() * 2
        elif stype == GeomAbs_Sphere:
            info["radius"] = adaptor.Sphere().Radius()
        elif stype == GeomAbs_Torus:
            info["major_r"] = adaptor.Torus().MajorRadius()
            info["minor_r"] = adaptor.Torus().MinorRadius()
        elif stype == GeomAbs_Cone:
            info["semi_angle_deg"] = math.degrees(adaptor.Cone().SemiAngle())
        faces.append(info)
        explorer.Next()
    faces.sort(key=lambda f: (f["type"], -f["area"]))
    return faces


def _cross_section_area(shape, axis_pos, plane_maker):
    plane = plane_maker(axis_pos)
    section = BRepAlgoAPI_Section(shape.wrapped, plane, False)
    section.ComputePCurveOn1(True)
    section.Approximation(True)
    section.Build()
    if not section.IsDone():
        return 0.0

    result_shape = section.Shape()
    edges_seq = TopTools_HSequenceOfShape()
    wires_seq = TopTools_HSequenceOfShape()
    edge_exp = TopExp_Explorer(result_shape, TopAbs_EDGE)
    while edge_exp.More():
        edges_seq.Append(edge_exp.Current())
        edge_exp.Next()
    if edges_seq.Length() == 0:
        return 0.0

    ShapeAnalysis_FreeBounds.ConnectEdgesToWires_s(
        edges_seq, 1e-4, False, wires_seq
    )
    total_area = 0.0
    for w_idx in range(1, wires_seq.Length() + 1):
        wire = TopoDS.Wire_s(wires_seq.Value(w_idx))
        try:
            face_maker = BRepBuilderAPI_MakeFace(plane, wire, True)
            if face_maker.IsDone():
                face_props = GProp_GProps()
                BRepGProp.SurfaceProperties_s(face_maker.Face(), face_props)
                total_area += abs(face_props.Mass())
        except Exception:
            continue
    return total_area


def _radial_distance(shape, origin, direction, max_r=20.0):
    line = gp_Lin(origin, direction)
    intersector = IntCurvesFace_ShapeIntersector()
    intersector.Load(shape.wrapped, 1e-6)
    intersector.PerformNearest(line, 0.0, max_r)
    if intersector.NbPnt() > 0:
        pt = intersector.Pnt(1)
        dx = pt.X() - origin.X()
        dy = pt.Y() - origin.Y()
        dz = pt.Z() - origin.Z()
        return math.sqrt(dx * dx + dy * dy + dz * dz)
    return None


# ═══════════════════════════════════════════════════════════
# Tests for peghead
# ═══════════════════════════════════════════════════════════

class TestGlobalProperties:
    """Volume, surface area, bounding box, center of mass."""

    def test_volume(self, part_under_test):
        vol_props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, vol_props)
        vol = vol_props.Mass()
        assert abs(vol - REF_VOLUME) / REF_VOLUME < 0.01, (
            f"Volume {vol:.4f} differs from ref {REF_VOLUME} by {abs(vol - REF_VOLUME) / REF_VOLUME * 100:.1f}%"
        )

    def test_surface_area(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.SurfaceProperties_s(part_under_test.wrapped, props)
        area = props.Mass()
        assert abs(area - REF_SURFACE_AREA) / REF_SURFACE_AREA < 0.02, (
            f"Surface area {area:.4f} differs from ref {REF_SURFACE_AREA}"
        )

    def test_bounding_box(self, part_under_test):
        bb = part_under_test.bounding_box()
        tol = 0.1
        assert abs(bb.min.X - REF_BBOX_MIN[0]) < tol, "BBox min X mismatch"
        assert abs(bb.max.X - REF_BBOX_MAX[0]) < tol, "BBox max X mismatch"
        assert abs(bb.min.Y - REF_BBOX_MIN[1]) < tol, "BBox min Y mismatch"
        assert abs(bb.max.Y - REF_BBOX_MAX[1]) < tol, "BBox max Y mismatch"
        assert abs(bb.min.Z - REF_BBOX_MIN[2]) < tol, "BBox min Z mismatch"
        assert abs(bb.max.Z - REF_BBOX_MAX[2]) < tol, "BBox max Z mismatch"

    def test_center_of_mass(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, props)
        com = props.CentreOfMass()
        for i, (actual, ref) in enumerate(zip(
            (com.X(), com.Y(), com.Z()), REF_CENTER_OF_MASS)):
            assert abs(actual - ref) < 0.2, (
                f"CoM axis {i}: {actual:.4f} vs ref {ref:.4f}"
            )


class TestMomentsOfInertia:
    """Inertia tensor — very sensitive to mass distribution."""

    def test_principal_moments(self, part_under_test):
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(part_under_test.wrapped, props)
        mat = props.MatrixOfInertia()
        for key, (r, c) in [("Ixx", (1,1)), ("Iyy", (2,2)), ("Izz", (3,3))]:
            actual = mat.Value(r, c)
            ref = REF_INERTIA[key]
            if abs(ref) > 1e-6:
                assert abs(actual - ref) / abs(ref) < 0.02, (
                    f"{key}: {actual:.4f} vs ref {ref:.4f}"
                )


class TestFaceInventory:
    """Face types, counts, and key dimensions."""

    def test_face_count(self, part_under_test):
        faces = _get_face_inventory(part_under_test)
        assert abs(len(faces) - REF_FACE_COUNT) <= 3, (
            f"Face count {len(faces)} vs ref {REF_FACE_COUNT}"
        )

    def test_face_type_distribution(self, part_under_test):
        faces = _get_face_inventory(part_under_test)
        actual = {}
        for f in faces:
            actual[f["type"]] = actual.get(f["type"], 0) + 1
        ref = {}
        for f in REF_FACE_INVENTORY:
            ref[f["type"]] = ref.get(f["type"], 0) + 1
        for ftype, count in ref.items():
            assert abs(actual.get(ftype, 0) - count) <= 2, (
                f"{ftype} count: {actual.get(ftype, 0)} vs ref {count}"
            )

    def test_cylinder_diameters(self, part_under_test):
        """Every reference cylinder diameter should appear."""
        faces = _get_face_inventory(part_under_test)
        actual_diams = sorted(f["diameter"] for f in faces if "diameter" in f)
        ref_diams = sorted(f["diameter"] for f in REF_FACE_INVENTORY if "diameter" in f)
        for rd in ref_diams:
            assert any(abs(ad - rd) < 0.1 for ad in actual_diams), (
                f"Reference cylinder d={rd:.3f} not found in actual: {actual_diams}"
            )


class TestCrossSections:
    """Cross-sectional area at 20 positions along Z."""

    _plane_maker = staticmethod(lambda v: gp_Pln(gp_Pnt(0, 0, v), gp_Dir(0, 0, 1)))

    @pytest.mark.parametrize("ref", REF_CROSS_SECTIONS,
        ids=[f"Z={cs['position']}" for cs in REF_CROSS_SECTIONS])
    def test_cross_section_area(self, part_under_test, ref):
        area = _cross_section_area(part_under_test, ref["position"], self._plane_maker)
        ref_area = ref["area"]
        if ref_area < 0.01:  # near-zero slice
            assert area < 0.5, f"Expected ~0 area at pos={ref['position']}, got {area:.4f}"
        else:
            assert abs(area - ref_area) / ref_area < 0.03, (
                f"Area at Z={ref['position']}: {area:.4f} vs ref {ref_area:.4f} "
                f"({abs(area - ref_area) / ref_area * 100:.1f}% off)"
            )


class TestRadialProfile:
    """Radial distance from axis at 15 positions × 12 angles."""

    @pytest.mark.parametrize("ref", REF_RADIAL_PROFILE,
        ids=[f"Z={rp['position']}" for rp in REF_RADIAL_PROFILE])
    def test_radial_profile(self, part_under_test, ref):
        pos = ref["position"]
        for deg_str, ref_r in ref["radii"].items():
            deg = float(deg_str)
            if ref_r is None:
                continue
            origin = gp_Pnt(0, 0, pos)
            direction = gp_Dir(math.cos(math.radians(deg)), math.sin(math.radians(deg)), 0)
            actual_r = _radial_distance(part_under_test, origin, direction)
            assert actual_r is not None, (
                f"No intersection at Z={pos}, angle={deg}°"
            )
            assert abs(actual_r - ref_r) < 0.15, (
                f"Radial at Z={pos} angle={deg}°: {actual_r:.4f} vs ref {ref_r:.4f}"
            )
