"""Generate pytest test files from a CadFingerprint.

The generated test file is self-contained: it embeds the reference
fingerprint data and imports only build123d + OCCT. A user provides
their procedural implementation as a fixture.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Optional

from .fingerprint import CadFingerprint


def _fmt_float(v: float, decimals: int = 4) -> str:
    return f"{v:.{decimals}f}"


def _fmt_tuple(t: tuple, decimals: int = 4) -> str:
    return "(" + ", ".join(_fmt_float(v, decimals) for v in t) + ")"


def generate_test_file(
    fingerprint: CadFingerprint,
    output_path: Optional[str | Path] = None,
    module_name: str = "my_part",
    fixture_name: str = "part_under_test",
    axis: str = "Z",
    volume_tol_pct: float = 1.0,
    area_tol_pct: float = 2.0,
    bbox_tol_mm: float = 0.1,
    inertia_tol_pct: float = 2.0,
    cross_section_area_tol_pct: float = 3.0,
    cross_section_centroid_tol_mm: float = 0.2,
    cross_section_moment_tol_pct: float = 5.0,
    radial_tol_mm: float = 0.15,
    face_area_tol_pct: float = 5.0,
) -> str:
    """Generate a pytest file that validates a Part against the fingerprint.

    The generated file expects a conftest.py fixture named `fixture_name`
    that returns a build123d Part to test.

    Args:
        fingerprint: Reference fingerprint to test against.
        output_path: If provided, write the test file here.
        module_name: Human-readable name for the part (used in comments).
        fixture_name: pytest fixture name that provides the Part under test.
        axis: Primary axis of the part (used in comments).
        volume_tol_pct: Volume tolerance in percent.
        area_tol_pct: Surface area tolerance in percent.
        bbox_tol_mm: Bounding box tolerance in mm.
        inertia_tol_pct: Moment of inertia tolerance in percent.
        cross_section_area_tol_pct: Cross-section area tolerance in percent.
        cross_section_centroid_tol_mm: Cross-section centroid tolerance in mm.
        radial_tol_mm: Radial profile tolerance in mm.
        face_area_tol_pct: Face area tolerance in percent.

    Returns:
        The generated test file content as a string.
    """
    fp = fingerprint
    va = fp.volume_and_area
    bb = fp.bounding_box
    moi = fp.moments_of_inertia
    topo = fp.topology

    lines = []

    # ── header ───────────────────────────────────────────────────────
    lines.append(f'"""Auto-generated geometric fingerprint tests for {module_name}.')
    lines.append("")
    lines.append(f"Generated by cad-fingerprint from: {fp.file}")
    lines.append(f"Reference volume: {va['volume']:.4f} mm³")
    lines.append(f"Reference surface area: {va['surface_area']:.4f} mm²")
    lines.append(f"Reference bounding box: {_fmt_tuple(bb['size'])} mm")
    lines.append("")
    lines.append("To use these tests, create a conftest.py with a fixture::")
    lines.append("")
    lines.append(f"    @pytest.fixture")
    lines.append(f"    def {fixture_name}():")
    lines.append(f"        # Return the Part to validate.")
    lines.append(f"        return my_build_function()")
    lines.append("")
    is_stl = getattr(fp, "source_format", "step") == "stl"

    lines.append("Any procedural implementation that passes all tests is")
    fmt = "STL mesh" if is_stl else "STEP file"
    lines.append(f"geometrically equivalent to the reference {fmt}.")
    if is_stl:
        lines.append("")
        lines.append("Note: Face inventory tests are omitted (STL has no analytical")
        lines.append("surface types). Cross-section and radial profile tests are fully")
        lines.append("functional.")
    lines.append('"""')
    lines.append("")

    # ── imports ──────────────────────────────────────────────────────
    lines.append("import math")
    lines.append("")
    lines.append("import pytest")
    lines.append("")
    lines.append("from build123d import Part")
    lines.append("from OCP.BRepAdaptor import BRepAdaptor_Curve, BRepAdaptor_Surface")
    lines.append("from OCP.BRepAlgoAPI import BRepAlgoAPI_Section")
    lines.append("from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeFace")
    lines.append("from OCP.BRepGProp import BRepGProp")
    lines.append("from OCP.GCPnts import GCPnts_AbscissaPoint")
    lines.append("from OCP.GeomAbs import (")
    lines.append("    GeomAbs_BSplineCurve, GeomAbs_BSplineSurface, GeomAbs_Circle,")
    lines.append("    GeomAbs_Cone, GeomAbs_Cylinder, GeomAbs_Ellipse,")
    lines.append("    GeomAbs_Line, GeomAbs_Plane, GeomAbs_Sphere, GeomAbs_Torus,")
    lines.append(")")
    lines.append("from OCP.GProp import GProp_GProps")
    lines.append("from OCP.IntCurvesFace import IntCurvesFace_ShapeIntersector")
    lines.append("from OCP.ShapeAnalysis import ShapeAnalysis_FreeBounds")
    lines.append("from OCP.TopAbs import TopAbs_EDGE, TopAbs_FACE, TopAbs_VERTEX")
    lines.append("from OCP.TopExp import TopExp_Explorer")
    lines.append("from OCP.TopTools import TopTools_HSequenceOfShape")
    lines.append("from OCP.TopoDS import TopoDS")
    lines.append("from OCP.gp import gp_Dir, gp_Lin, gp_Pln, gp_Pnt")
    lines.append("")
    lines.append("")

    # ── reference data ───────────────────────────────────────────────
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("# Reference fingerprint data")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("")

    lines.append(f"REF_VOLUME = {_fmt_float(va['volume'])}")
    lines.append(f"REF_SURFACE_AREA = {_fmt_float(va['surface_area'])}")
    lines.append(f"REF_CENTER_OF_MASS = {_fmt_tuple(va['center_of_mass'])}")
    lines.append(f"REF_BBOX_MIN = {_fmt_tuple(bb['min'])}")
    lines.append(f"REF_BBOX_MAX = {_fmt_tuple(bb['max'])}")
    lines.append(f"REF_BBOX_SIZE = {_fmt_tuple(bb['size'])}")
    lines.append("")

    lines.append("REF_INERTIA = {")
    for k in ("Ixx", "Iyy", "Izz", "Ixy", "Ixz", "Iyz"):
        lines.append(f'    "{k}": {_fmt_float(moi[k])},')
    lines.append("}")
    lines.append("")

    if not is_stl:
        lines.append(f"REF_FACE_COUNT = {topo['faces']}")
        lines.append(f"REF_EDGE_COUNT = {topo['edges']}")
        lines.append(f"REF_VERTEX_COUNT = {topo['vertices']}")
        lines.append("")

        lines.append("REF_FACE_INVENTORY = [")
        for f in fp.face_inventory:
            parts = [f'    {{"type": "{f["type"]}", "area": {_fmt_float(f["area"])}']
            if "diameter" in f:
                parts.append(f', "diameter": {_fmt_float(f["diameter"])}')
            if "radius" in f:
                parts.append(f', "radius": {_fmt_float(f["radius"])}')
            if "major_r" in f:
                parts.append(f', "major_r": {_fmt_float(f["major_r"])}')
                parts.append(f', "minor_r": {_fmt_float(f["minor_r"])}')
            if "semi_angle_deg" in f:
                parts.append(f', "semi_angle_deg": {_fmt_float(f["semi_angle_deg"], 2)}')
            parts.append("},")
            lines.append("".join(parts))
        lines.append("]")
        lines.append("")

    # Edge inventory
    lines.append("REF_EDGE_INVENTORY = [")
    for e in fp.edge_inventory:
        parts = [f'    {{"type": "{e["type"]}", "length": {_fmt_float(e["length"])}']
        if "radius" in e:
            parts.append(f', "radius": {_fmt_float(e["radius"])}')
        if "major_r" in e:
            parts.append(f', "major_r": {_fmt_float(e["major_r"])}')
            parts.append(f', "minor_r": {_fmt_float(e["minor_r"])}')
        parts.append("},")
        lines.append("".join(parts))
    lines.append("]")
    lines.append("")

    # Cross-sections
    lines.append("REF_CROSS_SECTIONS = [")
    for cs in fp.cross_sections:
        parts = [f'    {{"position": {_fmt_float(cs["position"])}, '
                 f'"area": {_fmt_float(cs["area"])}']
        # Add centroid and 2D moment keys dynamically
        for k, v in cs.items():
            if k.startswith("centroid_") or k.endswith("_2d"):
                parts.append(f', "{k}": {_fmt_float(v)}')
        parts.append("},")
        lines.append("".join(parts))
    lines.append("]")
    lines.append("")

    # Radial profile
    lines.append("REF_RADIAL_PROFILE = [")
    for rp in fp.radial_profile:
        radii_str = ", ".join(
            f"{deg}: {_fmt_float(r) if r is not None else 'None'}"
            for deg, r in sorted(rp["radii"].items(), key=lambda x: float(x[0]))
        )
        lines.append(f'    {{"position": {_fmt_float(rp["position"])}, '
                     f'"radii": {{{radii_str}}}}},')
    lines.append("]")
    lines.append("")
    lines.append("")

    # ── helpers ───────────────────────────────────────────────────────
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("# Test helpers")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("")

    lines.append(textwrap.dedent("""\
    _SURFACE_NAMES = {
        GeomAbs_Plane: "Plane",
        GeomAbs_Cylinder: "Cylinder",
        GeomAbs_Cone: "Cone",
        GeomAbs_Sphere: "Sphere",
        GeomAbs_Torus: "Torus",
        GeomAbs_BSplineSurface: "BSpline",
    }


    def _get_face_inventory(shape):
        explorer = TopExp_Explorer(shape.wrapped, TopAbs_FACE)
        faces = []
        while explorer.More():
            face = TopoDS.Face_s(explorer.Current())
            adaptor = BRepAdaptor_Surface(face)
            stype = adaptor.GetType()
            type_name = _SURFACE_NAMES.get(stype, f"Other({stype})")
            props = GProp_GProps()
            BRepGProp.SurfaceProperties_s(face, props)
            info = {"type": type_name, "area": props.Mass()}
            if stype == GeomAbs_Cylinder:
                info["diameter"] = adaptor.Cylinder().Radius() * 2
            elif stype == GeomAbs_Sphere:
                info["radius"] = adaptor.Sphere().Radius()
            elif stype == GeomAbs_Torus:
                info["major_r"] = adaptor.Torus().MajorRadius()
                info["minor_r"] = adaptor.Torus().MinorRadius()
            elif stype == GeomAbs_Cone:
                info["semi_angle_deg"] = math.degrees(adaptor.Cone().SemiAngle())
            faces.append(info)
            explorer.Next()
        faces.sort(key=lambda f: (f["type"], -f["area"]))
        return faces


    _CURVE_NAMES = {
        GeomAbs_Line: "Line",
        GeomAbs_Circle: "Circle",
        GeomAbs_Ellipse: "Ellipse",
        GeomAbs_BSplineCurve: "BSpline",
    }


    def _get_edge_inventory(shape):
        explorer = TopExp_Explorer(shape.wrapped, TopAbs_EDGE)
        edges = []
        while explorer.More():
            edge = TopoDS.Edge_s(explorer.Current())
            adaptor = BRepAdaptor_Curve(edge)
            ctype = adaptor.GetType()
            type_name = _CURVE_NAMES.get(ctype, f"Other({int(ctype)})")
            length = GCPnts_AbscissaPoint.Length_s(adaptor)
            info = {"type": type_name, "length": length}
            if ctype == GeomAbs_Circle:
                info["radius"] = adaptor.Circle().Radius()
            edges.append(info)
            explorer.Next()
        edges.sort(key=lambda e: (e["type"], -e["length"]))
        return edges


    def _cross_section_props(shape, axis_pos, plane_maker, uv_axes):
        # Return area, centroid, and 2D shape moments for a cross-section.
        _axis_idx = {"X": 1, "Y": 2, "Z": 3}
        u_idx = _axis_idx[uv_axes[0]]
        v_idx = _axis_idx[uv_axes[1]]
        zero = {"area": 0.0, "centroid_u": 0.0, "centroid_v": 0.0,
                "Iuu_2d": 0.0, "Ivv_2d": 0.0}
        plane = plane_maker(axis_pos)
        section = BRepAlgoAPI_Section(shape.wrapped, plane, False)
        section.ComputePCurveOn1(True)
        section.Approximation(True)
        section.Build()
        if not section.IsDone():
            return zero

        result_shape = section.Shape()
        edges_seq = TopTools_HSequenceOfShape()
        wires_seq = TopTools_HSequenceOfShape()
        edge_exp = TopExp_Explorer(result_shape, TopAbs_EDGE)
        while edge_exp.More():
            edges_seq.Append(edge_exp.Current())
            edge_exp.Next()
        if edges_seq.Length() == 0:
            return zero

        ShapeAnalysis_FreeBounds.ConnectEdgesToWires_s(
            edges_seq, 1e-4, False, wires_seq
        )
        total_area = 0.0
        total_cu = 0.0
        total_cv = 0.0
        total_Iuu = 0.0
        total_Ivv = 0.0
        for w_idx in range(1, wires_seq.Length() + 1):
            wire = TopoDS.Wire_s(wires_seq.Value(w_idx))
            try:
                face_maker = BRepBuilderAPI_MakeFace(plane, wire, True)
                if face_maker.IsDone():
                    face_shape = face_maker.Face()
                    face_props = GProp_GProps()
                    BRepGProp.SurfaceProperties_s(face_shape, face_props)
                    a = abs(face_props.Mass())
                    com = face_props.CentreOfMass()
                    u = getattr(com, uv_axes[0])()
                    v = getattr(com, uv_axes[1])()
                    total_area += a
                    total_cu += u * a
                    total_cv += v * a
                    mat = face_props.MatrixOfInertia()
                    total_Iuu += mat.Value(u_idx, u_idx)
                    total_Ivv += mat.Value(v_idx, v_idx)
            except Exception:
                continue
        cu = total_cu / total_area if total_area > 1e-9 else 0.0
        cv = total_cv / total_area if total_area > 1e-9 else 0.0
        return {"area": total_area, "centroid_u": cu, "centroid_v": cv,
                "Iuu_2d": total_Iuu, "Ivv_2d": total_Ivv}


    def _radial_distance(shape, origin, direction, max_r=20.0):
        line = gp_Lin(origin, direction)
        intersector = IntCurvesFace_ShapeIntersector()
        intersector.Load(shape.wrapped, 1e-6)
        intersector.PerformNearest(line, 0.0, max_r)
        if intersector.NbPnt() > 0:
            pt = intersector.Pnt(1)
            dx = pt.X() - origin.X()
            dy = pt.Y() - origin.Y()
            dz = pt.Z() - origin.Z()
            return math.sqrt(dx * dx + dy * dy + dz * dz)
        return None
    """))

    # ── test classes ─────────────────────────────────────────────────
    lines.append("")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append(f"# Tests for {module_name}")
    lines.append("# ═══════════════════════════════════════════════════════════")
    lines.append("")

    # -- Global properties
    lines.append(f"class TestGlobalProperties:")
    lines.append(f'    """Volume, surface area, bounding box, center of mass."""')
    lines.append("")
    lines.append(f"    def test_volume(self, {fixture_name}):")
    lines.append(f"        vol_props = GProp_GProps()")
    lines.append(f"        BRepGProp.VolumeProperties_s({fixture_name}.wrapped, vol_props)")
    lines.append(f"        vol = vol_props.Mass()")
    lines.append(f"        pct = abs(vol - REF_VOLUME) / REF_VOLUME * 100")
    lines.append(f"        direction = 'larger' if vol > REF_VOLUME else 'smaller'")
    lines.append(f"        assert pct / 100 < {volume_tol_pct / 100}, (")
    lines.append(f'            f"Volume {{vol:.4f}} is {{direction}} than ref {{REF_VOLUME}} '
                 f'by {{abs(vol - REF_VOLUME):.2f}} mm³ ({{pct:.1f}}%) — adjust overall dimensions"')
    lines.append(f"        )")
    lines.append("")

    lines.append(f"    def test_surface_area(self, {fixture_name}):")
    lines.append(f"        props = GProp_GProps()")
    lines.append(f"        BRepGProp.SurfaceProperties_s({fixture_name}.wrapped, props)")
    lines.append(f"        area = props.Mass()")
    lines.append(f"        pct = abs(area - REF_SURFACE_AREA) / REF_SURFACE_AREA * 100")
    lines.append(f"        direction = 'larger' if area > REF_SURFACE_AREA else 'smaller'")
    lines.append(f"        assert pct / 100 < {area_tol_pct / 100}, (")
    lines.append(f'            f"Surface area {{area:.4f}} is {{direction}} than ref {{REF_SURFACE_AREA}} '
                 f'({{pct:.1f}}% off) — check feature dimensions"')
    lines.append(f"        )")
    lines.append("")

    lines.append(f"    def test_bounding_box(self, {fixture_name}):")
    lines.append(f"        bb = {fixture_name}.bounding_box()")
    lines.append(f"        tol = {bbox_tol_mm}")
    for i, axis_name in enumerate(("X", "Y", "Z")):
        lines.append(f"        assert abs(bb.min.{axis_name} - REF_BBOX_MIN[{i}]) < tol, "
                     f'"BBox min {axis_name} mismatch"')
        lines.append(f"        assert abs(bb.max.{axis_name} - REF_BBOX_MAX[{i}]) < tol, "
                     f'"BBox max {axis_name} mismatch"')
    lines.append("")

    lines.append(f"    def test_center_of_mass(self, {fixture_name}):")
    lines.append(f"        props = GProp_GProps()")
    lines.append(f"        BRepGProp.VolumeProperties_s({fixture_name}.wrapped, props)")
    lines.append(f"        com = props.CentreOfMass()")
    lines.append(f"        for i, (actual, ref) in enumerate(zip(")
    lines.append(f"            (com.X(), com.Y(), com.Z()), REF_CENTER_OF_MASS)):")
    lines.append(f"            assert abs(actual - ref) < {bbox_tol_mm * 2}, (")
    lines.append(f'                f"CoM axis {{i}}: {{actual:.4f}} vs ref {{ref:.4f}}"')
    lines.append(f"            )")
    lines.append("")

    # -- Moments of inertia
    lines.append("")
    lines.append(f"class TestMomentsOfInertia:")
    lines.append(f'    """Inertia tensor — very sensitive to mass distribution."""')
    lines.append("")
    lines.append(f"    def test_principal_moments(self, {fixture_name}):")
    lines.append(f"        props = GProp_GProps()")
    lines.append(f"        BRepGProp.VolumeProperties_s({fixture_name}.wrapped, props)")
    lines.append(f"        mat = props.MatrixOfInertia()")
    lines.append(f"        for key, (r, c) in [(\"Ixx\", (1,1)), (\"Iyy\", (2,2)), (\"Izz\", (3,3))]:")
    lines.append(f"            actual = mat.Value(r, c)")
    lines.append(f"            ref = REF_INERTIA[key]")
    lines.append(f"            if abs(ref) > 1e-6:")
    lines.append(f"                pct = abs(actual - ref) / abs(ref) * 100")
    lines.append(f"                assert pct / 100 < {inertia_tol_pct / 100}, (")
    lines.append(f'                    f"{{key}}: {{actual:.4f}} vs ref {{ref:.4f}} ({{pct:.1f}}% off) — mass distribution differs"')
    lines.append(f"                )")
    lines.append("")

    lines.append(f"    def test_off_diagonal_moments(self, {fixture_name}):")
    lines.append(f"        props = GProp_GProps()")
    lines.append(f"        BRepGProp.VolumeProperties_s({fixture_name}.wrapped, props)")
    lines.append(f"        mat = props.MatrixOfInertia()")
    lines.append(f"        for key, (r, c) in [(\"Ixy\", (1,2)), (\"Ixz\", (1,3)), (\"Iyz\", (2,3))]:")
    lines.append(f"            actual = mat.Value(r, c)")
    lines.append(f"            ref = REF_INERTIA[key]")
    lines.append(f"            tol = max(abs(ref) * {inertia_tol_pct / 100}, 1.0)")
    lines.append(f"            assert abs(actual - ref) < tol, (")
    lines.append(f'                f"{{key}}: {{actual:.4f}} vs ref {{ref:.4f}} — part may be rotated or asymmetric"')
    lines.append(f"            )")
    lines.append("")

    # -- Face inventory (STEP only — STL has no analytical surface types)
    if not is_stl:
        lines.append("")
        lines.append(f"class TestFaceInventory:")
        lines.append(f'    """Face types, counts, and key dimensions."""')
        lines.append("")
        lines.append(f"    def test_face_count(self, {fixture_name}):")
        lines.append(f"        faces = _get_face_inventory({fixture_name})")
        lines.append(f"        diff = len(faces) - REF_FACE_COUNT")
        lines.append(f"        label = 'extra' if diff > 0 else 'missing'")
        lines.append(f"        assert abs(diff) <= 3, (")
        lines.append(f'            f"Face count {{len(faces)}} vs ref {{REF_FACE_COUNT}} ({{label}} {{abs(diff)}}) — check boolean operations and fillets"')
        lines.append(f"        )")
        lines.append("")

        lines.append(f"    def test_face_type_distribution(self, {fixture_name}):")
        lines.append(f"        faces = _get_face_inventory({fixture_name})")
        lines.append(f"        actual = {{}}")
        lines.append(f"        for f in faces:")
        lines.append(f'            actual[f["type"]] = actual.get(f["type"], 0) + 1')
        lines.append(f"        ref = {{}}")
        lines.append(f"        for f in REF_FACE_INVENTORY:")
        lines.append(f'            ref[f["type"]] = ref.get(f["type"], 0) + 1')
        lines.append(f"        for ftype, count in ref.items():")
        lines.append(f"            actual_count = actual.get(ftype, 0)")
        lines.append(f"            assert abs(actual_count - count) <= 2, (")
        lines.append(f'                f"{{ftype}} count: {{actual_count}} vs ref {{count}} — check boolean operations and fillets"')
        lines.append(f"            )")
        lines.append("")

        lines.append(f"    def test_cylinder_diameters(self, {fixture_name}):")
        lines.append(f'        """Every reference cylinder diameter should appear."""')
        lines.append(f"        faces = _get_face_inventory({fixture_name})")
        lines.append(f'        actual_diams = sorted(f["diameter"] for f in faces if "diameter" in f)')
        lines.append(f'        ref_diams = sorted(f["diameter"] for f in REF_FACE_INVENTORY if "diameter" in f)')
        lines.append(f"        for rd in ref_diams:")
        lines.append(f"            assert any(abs(ad - rd) < 0.1 for ad in actual_diams), (")
        lines.append(f'                f"Reference cylinder d={{rd:.3f}} not found in actual: {{actual_diams}}"')
        lines.append(f"            )")
        lines.append("")

    # -- Edge inventory
    if fp.edge_inventory:
        lines.append("")
        lines.append(f"class TestEdgeInventory:")
        lines.append(f'    """Edge types, counts, and key dimensions."""')
        lines.append("")

        lines.append(f"    def test_edge_type_distribution(self, {fixture_name}):")
        lines.append(f"        edges = _get_edge_inventory({fixture_name})")
        lines.append(f"        actual = {{}}")
        lines.append(f"        for e in edges:")
        lines.append(f'            actual[e["type"]] = actual.get(e["type"], 0) + 1')
        lines.append(f"        ref = {{}}")
        lines.append(f"        for e in REF_EDGE_INVENTORY:")
        lines.append(f'            ref[e["type"]] = ref.get(e["type"], 0) + 1')
        lines.append(f"        for etype, count in ref.items():")
        lines.append(f"            actual_count = actual.get(etype, 0)")
        lines.append(f"            assert abs(actual_count - count) <= max(2, count // 5), (")
        lines.append(f'                f"{{etype}} edge count: {{actual_count}} vs ref {{count}}"')
        lines.append(f"            )")
        lines.append("")

        lines.append(f"    def test_circle_edge_radii(self, {fixture_name}):")
        lines.append(f'        """Every reference circle-edge radius should appear."""')
        lines.append(f"        edges = _get_edge_inventory({fixture_name})")
        lines.append(f'        actual_radii = sorted(e["radius"] for e in edges if "radius" in e)')
        lines.append(f'        ref_radii = sorted(e["radius"] for e in REF_EDGE_INVENTORY if "radius" in e)')
        lines.append(f"        for rr in set(round(r, 2) for r in ref_radii):")
        lines.append(f"            assert any(abs(ar - rr) < 0.1 for ar in actual_radii), (")
        lines.append(f'                f"Reference circle edge r={{rr:.3f}} not found in actual"')
        lines.append(f"            )")
        lines.append("")

    # -- Cross-sections
    lines.append("")
    lines.append(f"class TestCrossSections:")
    lines.append(f'    """Cross-sectional area and centroid at {len(fp.cross_sections)} positions along {axis}."""')
    lines.append("")

    # Determine plane maker and UV axes based on axis
    if axis.upper() == "Z":
        plane_maker = 'lambda v: gp_Pln(gp_Pnt(0, 0, v), gp_Dir(0, 0, 1))'
        uv_axes = '("X", "Y")'
        centroid_keys = ("centroid_x", "centroid_y")
    elif axis.upper() == "Y":
        plane_maker = 'lambda v: gp_Pln(gp_Pnt(0, v, 0), gp_Dir(0, 1, 0))'
        uv_axes = '("X", "Z")'
        centroid_keys = ("centroid_x", "centroid_z")
    else:
        plane_maker = 'lambda v: gp_Pln(gp_Pnt(v, 0, 0), gp_Dir(1, 0, 0))'
        uv_axes = '("Y", "Z")'
        centroid_keys = ("centroid_y", "centroid_z")

    lines.append(f"    _plane_maker = staticmethod({plane_maker})")
    lines.append(f"    _uv_axes = {uv_axes}")
    lines.append("")

    lines.append(f"    @pytest.mark.parametrize(\"ref\", REF_CROSS_SECTIONS,")
    lines.append(f'        ids=[f"{axis}={{cs[\'position\']}}" for cs in REF_CROSS_SECTIONS])')
    lines.append(f"    def test_cross_section_area(self, {fixture_name}, ref):")
    lines.append(f"        props = _cross_section_props({fixture_name}, ref[\"position\"], self._plane_maker, self._uv_axes)")
    lines.append(f'        area = props["area"]')
    lines.append(f'        ref_area = ref["area"]')
    lines.append(f"        if ref_area < 0.01:  # near-zero slice")
    lines.append(f"            assert area < 0.5, f\"Expected ~0 area at pos={{ref['position']}}, got {{area:.4f}}\"")
    lines.append(f"        else:")
    lines.append(f"            pct = abs(area - ref_area) / ref_area * 100")
    lines.append(f"            direction = 'too large' if area > ref_area else 'too small'")
    lines.append(f"            assert pct / 100 < {cross_section_area_tol_pct / 100}, (")
    lines.append(f'                f"Area at {axis}={{ref[\'position\']}}: {{area:.4f}} vs ref {{ref_area:.4f}} "')
    lines.append(f'                f"({{pct:.1f}}% {{direction}}) — adjust radius/fillet at this position"')
    lines.append(f"            )")
    lines.append("")

    lines.append(f"    @pytest.mark.parametrize(\"ref\", REF_CROSS_SECTIONS,")
    lines.append(f'        ids=[f"{axis}={{cs[\'position\']}}" for cs in REF_CROSS_SECTIONS])')
    lines.append(f"    def test_cross_section_centroid(self, {fixture_name}, ref):")
    lines.append(f'        ref_area = ref["area"]')
    lines.append(f"        if ref_area < 0.01:")
    lines.append(f"            pytest.skip(\"near-zero area — centroid meaningless\")")
    lines.append(f"        props = _cross_section_props({fixture_name}, ref[\"position\"], self._plane_maker, self._uv_axes)")
    lines.append(f'        for ref_key, prop_key in [("{centroid_keys[0]}", "centroid_u"), ("{centroid_keys[1]}", "centroid_v")]:')
    lines.append(f'            actual = props[prop_key]')
    lines.append(f'            ref_val = ref[ref_key]')
    lines.append(f"            diff = actual - ref_val")
    lines.append(f"            assert abs(diff) < {cross_section_centroid_tol_mm}, (")
    lines.append(f'                f"Centroid {{ref_key}} at {axis}={{ref[\'position\']}}: {{actual:.4f}} vs ref {{ref_val:.4f}} "')
    lines.append(f'                f"(shifted {{\'positive\' if diff > 0 else \'negative\'}} by {{abs(diff):.3f}}mm) — check alignment"')
    lines.append(f"            )")
    lines.append("")

    # Determine 2D moment keys based on axis
    if axis.upper() == "Z":
        moment_keys = ("Ixx_2d", "Iyy_2d")
    elif axis.upper() == "Y":
        moment_keys = ("Ixx_2d", "Izz_2d")
    else:
        moment_keys = ("Iyy_2d", "Izz_2d")

    lines.append(f"    @pytest.mark.parametrize(\"ref\", REF_CROSS_SECTIONS,")
    lines.append(f'        ids=[f"{axis}={{cs[\'position\']}}" for cs in REF_CROSS_SECTIONS])')
    lines.append(f"    def test_cross_section_shape(self, {fixture_name}, ref):")
    lines.append(f'        """2D moments capture cross-section shape, not just area."""')
    lines.append(f'        ref_area = ref["area"]')
    lines.append(f"        if ref_area < 0.01:")
    lines.append(f"            pytest.skip(\"near-zero area — shape moments meaningless\")")
    lines.append(f"        props = _cross_section_props({fixture_name}, ref[\"position\"], self._plane_maker, self._uv_axes)")
    lines.append(f'        for ref_key, prop_key in [("{moment_keys[0]}", "Iuu_2d"), ("{moment_keys[1]}", "Ivv_2d")]:')
    lines.append(f'            ref_val = ref.get(ref_key, 0.0)')
    lines.append(f"            if abs(ref_val) < 0.01:")
    lines.append(f"                continue")
    lines.append(f'            actual = props[prop_key]')
    lines.append(f"            pct = abs(actual - ref_val) / abs(ref_val) * 100")
    lines.append(f"            assert pct / 100 < {cross_section_moment_tol_pct / 100}, (")
    lines.append(f'                f"Shape moment {{ref_key}} at {axis}={{ref[\'position\']}}: {{actual:.4f}} vs ref {{ref_val:.4f}} "')
    lines.append(f'                f"({{pct:.1f}}% off) — cross-section shape differs"')
    lines.append(f"            )")
    lines.append("")

    # -- Radial profile
    lines.append("")
    lines.append(f"class TestRadialProfile:")
    lines.append(f'    """Radial distance from axis at {len(fp.radial_profile)} positions × '
                 f'{len(fp.radial_profile[0]["radii"]) if fp.radial_profile else 0} angles."""')
    lines.append("")

    if axis.upper() == "Z":
        origin_fn = "gp_Pnt(0, 0, pos)"
        dir_fn = "gp_Dir(math.cos(math.radians(deg)), math.sin(math.radians(deg)), 0)"
    elif axis.upper() == "Y":
        origin_fn = "gp_Pnt(0, pos, 0)"
        dir_fn = "gp_Dir(math.cos(math.radians(deg)), 0, math.sin(math.radians(deg)))"
    else:
        origin_fn = "gp_Pnt(pos, 0, 0)"
        dir_fn = "gp_Dir(0, math.cos(math.radians(deg)), math.sin(math.radians(deg)))"

    lines.append(f"    @pytest.mark.parametrize(\"ref\", REF_RADIAL_PROFILE,")
    lines.append(f'        ids=[f"{axis}={{rp[\'position\']}}" for rp in REF_RADIAL_PROFILE])')
    lines.append(f"    def test_radial_profile(self, {fixture_name}, ref):")
    lines.append(f'        pos = ref["position"]')
    lines.append(f'        for deg_str, ref_r in ref["radii"].items():')
    lines.append(f"            deg = float(deg_str)")
    lines.append(f"            if ref_r is None:")
    lines.append(f"                continue")
    lines.append(f"            origin = {origin_fn}")
    lines.append(f"            direction = {dir_fn}")
    lines.append(f"            actual_r = _radial_distance({fixture_name}, origin, direction)")
    lines.append(f"            assert actual_r is not None, (")
    lines.append(f'                f"No intersection at {axis}={{pos}}, angle={{deg}}°"')
    lines.append(f"            )")
    lines.append(f"            hint = 'excess' if actual_r > ref_r else 'missing'")
    lines.append(f"            assert abs(actual_r - ref_r) < {radial_tol_mm}, (")
    lines.append(f'                f"Radial at {axis}={{pos}} angle={{deg}}°: '
                 f'{{actual_r:.4f}} vs ref {{ref_r:.4f}} — {{hint}} material"')
    lines.append(f"            )")
    lines.append("")

    # -- Build quality
    bq = fingerprint.build_quality
    if bq:
        lines.append("")
        lines.append(f"class TestBuildQuality:")
        lines.append(f'    """Solid validity, watertight check, single body."""')
        lines.append("")

        # Additional imports needed for build quality tests
        lines.append(f"    def test_single_solid(self, {fixture_name}):")
        lines.append(f'        """Result must be a single solid (not split by failed booleans)."""')
        lines.append(f"        from OCP.TopAbs import TopAbs_SOLID")
        lines.append(f"        exp = TopExp_Explorer({fixture_name}.wrapped, TopAbs_SOLID)")
        lines.append(f"        count = 0")
        lines.append(f"        while exp.More():")
        lines.append(f"            count += 1")
        lines.append(f"            exp.Next()")
        lines.append(f"        assert count == {bq.get('solid_count', 1)}, (")
        lines.append(f'            f"Expected {bq.get("solid_count", 1)} solid(s), got {{count}}"')
        lines.append(f"        )")
        lines.append("")

        lines.append(f"    def test_no_free_edges(self, {fixture_name}):")
        lines.append(f'        """No free edges — the solid must be watertight."""')
        lines.append(f"        from OCP.ShapeAnalysis import ShapeAnalysis_FreeBounds")
        lines.append(f"        fb = ShapeAnalysis_FreeBounds({fixture_name}.wrapped)")
        lines.append(f"        open_wires = fb.GetOpenWires()")
        lines.append(f"        exp = TopExp_Explorer(open_wires, TopAbs_EDGE)")
        lines.append(f"        free_count = 0")
        lines.append(f"        while exp.More():")
        lines.append(f"            free_count += 1")
        lines.append(f"            exp.Next()")
        lines.append(f"        assert free_count == 0, (")
        lines.append(f'            f"Found {{free_count}} free edge(s) — solid is not watertight"')
        lines.append(f"        )")
        lines.append("")

        lines.append(f"    def test_shape_valid(self, {fixture_name}):")
        lines.append(f'        """OCCT validity check — no degenerate or corrupt geometry."""')
        lines.append(f"        from OCP.BRepCheck import BRepCheck_Analyzer")
        lines.append(f"        analyzer = BRepCheck_Analyzer({fixture_name}.wrapped)")
        lines.append(f"        assert analyzer.IsValid(), \"BRepCheck_Analyzer reports invalid geometry\"")
        lines.append("")

        if "step_file_bytes" in bq:
            ref_bytes = bq["step_file_bytes"]
            max_bytes = ref_bytes * 4
            lines.append(f"    def test_step_file_size(self, {fixture_name}, tmp_path):")
            lines.append(f'        """STEP file size must not balloon (catches BSpline bloat)."""')
            lines.append(f"        import os")
            lines.append(f"        from OCP.STEPControl import STEPControl_Writer, STEPControl_ManifoldSolidBrep")
            lines.append(f"        from OCP.Interface import Interface_Static")
            lines.append(f"        out = os.path.join(str(tmp_path), \"test_export.step\")")
            lines.append(f"        writer = STEPControl_Writer()")
            lines.append(f'        Interface_Static.SetCVal_s("write.step.schema", "AP203")')
            lines.append(f"        writer.Transfer({fixture_name}.wrapped, STEPControl_ManifoldSolidBrep)")
            lines.append(f"        writer.Write(out)")
            lines.append(f"        size = os.path.getsize(out)")
            lines.append(f"        assert size < {max_bytes}, (")
            lines.append(f'            f"STEP file {{size // 1024}}KB exceeds {max_bytes // 1024}KB limit '
                         f'(ref was {ref_bytes // 1024}KB)"')
            lines.append(f"        )")
            lines.append("")

    content = "\n".join(lines)

    if output_path:
        Path(output_path).write_text(content)

    return content


def generate_prompt(
    fingerprint: "CadFingerprint",
    output_path: Optional[str | Path] = None,
    module_name: str = "my_part",
    axis: str = "Z",
) -> str:
    """Generate a generic prompt for an AI to recreate the STEP geometry.

    The prompt describes the part structure, key dimensions, build quality
    rules, and how to use the test suite. It is derived entirely from the
    fingerprint data — no manual description needed.
    """
    fp = fingerprint
    va = fp.volume_and_area
    bb = fp.bounding_box
    desc = fp.description
    bq = fp.build_quality

    lines = []
    lines.append(f"# Reverse-Engineer a STEP File into build123d")
    lines.append("")
    lines.append("## Goal")
    lines.append("")
    lines.append(f"Recreate the geometry in the reference STEP file as procedural "
                 f"build123d Python code. The test suite in `test_{module_name}.py` "
                 f"defines geometric assertions that your implementation must pass.")
    lines.append("")

    # ── Part overview ──
    lines.append("## Part Overview")
    lines.append("")
    lines.append(f"- **Bounding box**: {bb['size'][0]:.1f} × {bb['size'][1]:.1f} × "
                 f"{bb['size'][2]:.1f} mm")
    lines.append(f"- **Volume**: {va['volume']:.1f} mm³")
    lines.append(f"- **Surface area**: {va['surface_area']:.1f} mm²")
    lines.append(f"- **Faces**: {desc.get('face_count', '?')} "
                 f"({desc.get('bspline_count', 0)} BSpline / complex)")
    lines.append(f"- **Primary axis**: {axis}")
    lines.append("")

    # ── Key dimensions ──
    lines.append("## Key Dimensions (extracted from fingerprint)")
    lines.append("")

    if desc.get("cylinder_features"):
        lines.append("### Cylindrical features")
        lines.append("")
        lines.append("| Diameter | Surface area | Likely feature |")
        lines.append("|----------|-------------|----------------|")
        for c in desc["cylinder_features"]:
            lines.append(f"| {c['diameter']:.2f} mm | {c['area']:.1f} mm² | |")
        lines.append("")

    if desc.get("sphere_features"):
        lines.append("### Spherical features")
        lines.append("")
        for s in desc["sphere_features"]:
            lines.append(f"- Sphere radius {s['radius']:.2f} mm (area {s['area']:.1f} mm²)")
        lines.append("")

    if desc.get("fillet_features"):
        lines.append("### Fillets (torus faces)")
        lines.append("")
        lines.append("| Major radius | Minor radius | Surface area |")
        lines.append("|-------------|-------------|-------------|")
        for f in desc["fillet_features"]:
            lines.append(f"| {f['major_r']:.2f} mm | {f['minor_r']:.2f} mm | {f['area']:.1f} mm² |")
        lines.append("")

    if desc.get("bspline_count", 0) > 0:
        lines.append(f"### Complex surfaces")
        lines.append("")
        lines.append(f"The part has {desc['bspline_count']} BSpline face(s). "
                     f"These are sculpted/blended surfaces that cannot be represented "
                     f"as simple primitives. They may result from fillets on complex "
                     f"edge intersections (e.g. sphere-plane), lofts, or sweeps.")
        lines.append("")

    if desc.get("transitions"):
        lines.append("### Profile transitions")
        lines.append("")
        lines.append(f"Significant cross-section area changes along the {axis} axis:")
        lines.append("")
        for t in desc["transitions"]:
            lines.append(f"- At {axis}={t['position']:.1f}: "
                         f"area {t['from_area']:.1f} → {t['to_area']:.1f} mm²")
        lines.append("")

    # Edge summary
    if fp.edge_inventory:
        edge_types = {}
        for e in fp.edge_inventory:
            edge_types[e["type"]] = edge_types.get(e["type"], 0) + 1
        lines.append("### Edge summary")
        lines.append("")
        parts = [f"{count} {etype}" for etype, count in sorted(edge_types.items())]
        lines.append(f"The part has {sum(edge_types.values())} edges: {', '.join(parts)}.")
        circle_radii = sorted(set(
            round(e["radius"], 2) for e in fp.edge_inventory if "radius" in e
        ))
        if circle_radii:
            lines.append(f"- Circle edge radii (possible fillets/rounds): "
                         f"{', '.join(f'{r:.2f}mm' for r in circle_radii)}")
        lines.append("")

    # ── Process ──
    lines.append("## Process")
    lines.append("")
    lines.append("1. **Study the fingerprint data** in the test file. The reference "
                 "data tells you everything about the shape:")
    lines.append("   - `REF_FACE_INVENTORY` — every face type, area, and key "
                 "dimensions (diameters, radii)")
    lines.append("   - `REF_EDGE_INVENTORY` — every edge type, length, and "
                 "radii (circle edges indicate fillets/rounds)")
    lines.append("   - `REF_CROSS_SECTIONS` — cross-sectional area at multiple "
                 f"{axis} positions")
    lines.append("   - `REF_RADIAL_PROFILE` — outer radius at multiple positions × angles")
    lines.append("   - `REF_VOLUME`, `REF_SURFACE_AREA`, `REF_BBOX_*` — global properties")
    lines.append("   - `REF_INERTIA` — moments of inertia (very sensitive to mass distribution)")
    lines.append("")
    lines.append("2. **Create your implementation** in a new file that exports a "
                 "function returning a build123d `Part`.")
    lines.append("")
    lines.append("3. **Create a conftest.py** with a fixture:")
    lines.append("   ```python")
    lines.append("   import pytest")
    lines.append(f"   from my_implementation import create_{module_name}")
    lines.append("")
    lines.append("   @pytest.fixture")
    lines.append("   def part_under_test():")
    lines.append(f"       return create_{module_name}()")
    lines.append("   ```")
    lines.append("")
    lines.append(f"4. **Run the tests**: `pytest test_{module_name}.py -v`")
    lines.append("")
    lines.append("5. **Iterate**. Read the failures, adjust your code, repeat.")
    lines.append("")

    # ── Reading the fingerprint ──
    lines.append("## Tips for Reading the Fingerprint")
    lines.append("")
    lines.append("- **Cross-sections** show area vs position. Large jumps indicate "
                 "transitions between features. Constant areas indicate cylindrical "
                 "or prismatic sections.")
    lines.append("- **Radial profiles** show radius vs angle at each position. "
                 "Uniform radius = circular. Varying radius = sculpted/oval. "
                 "`None` values mean the ray missed (bore or concavity).")
    lines.append("- **Face inventory** lists every surface. BSpline faces are "
                 "sculpted regions — you may need `fillet`, `sweep`, or `loft` "
                 "operations, or accept that OCCT will approximate them as BSplines.")
    lines.append("- **Cylinder diameters** give you key feature sizes directly.")
    lines.append("- **Torus faces** are fillets/rounds — the minor radius is the "
                 "fillet radius.")
    lines.append("")

    # ── Build quality rules ──
    lines.append("## Build Quality Rules")
    lines.append("")
    lines.append("The test suite includes build quality checks. Follow these rules "
                 "to avoid common failures:")
    lines.append("")
    lines.append("### After every boolean (fuse, subtract, split)")
    lines.append("- Verify the result is a single solid. Boolean operations in "
                 "build123d can return `Compound`, `ShapeList`, or multiple solids.")
    lines.append("- Use a helper like `max(result.solids(), key=lambda s: s.volume)` "
                 "to extract the largest solid if needed.")
    lines.append("- Check for unexpected topology changes (face count, edge count).")
    lines.append("")
    lines.append("### After every fillet")
    lines.append("- Verify the fillet actually applied (face count should increase).")
    lines.append("- If OCCT produces BSpline surfaces where the reference has Torus "
                 "faces, consider alternative approaches (torus subtract, arcs in "
                 "revolve profiles).")
    lines.append("- Fillets on complex edge intersections (sphere-plane, cone-plane) "
                 "will almost always produce BSpline approximations.")
    lines.append("")
    lines.append("### STEP export")
    lines.append("- Use AP203 with `STEPControl_ManifoldSolidBrep` for best "
                 "compatibility.")
    lines.append("- Run `ShapeFix_Shape` before export to catch minor geometry issues.")
    if bq.get("step_file_bytes"):
        ref_kb = bq["step_file_bytes"] // 1024
        lines.append(f"- Reference STEP file is {ref_kb}KB. If your export is "
                     f"more than 4× this size, BSpline bloat is likely the cause.")
    lines.append("")

    # ── Success criteria ──
    lines.append("## What Success Looks Like")
    lines.append("")
    lines.append("All tests passing means your procedural code produces geometry "
                 "that is manufacturing-equivalent to the reference STEP file. "
                 "Minor surface representation differences are OK — the tolerances "
                 "are calibrated to accept these while catching real geometry errors.")
    lines.append("")

    content = "\n".join(lines)

    if output_path:
        Path(output_path).write_text(content)

    return content
